/* nd_btaudio.c -- see nd_btaudio.h. */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/types.h>

#include "nd_bt.h"
#include "nd_log.h"
#include "nd_paths.h"
#include "nd_proc.h"
#include <time.h>

#include "nd_vclock.h"

#include "nd_btaudio.h"

/* Write `text` to an ND_ROOT-resolved path, creating what it needs. */
static nd_err nd_btaudio_write_conf(const char *path, const char *text)
{
    char resolved[ND_PATH_MAX];
    FILE *f;

    if (nd_path_resolve(resolved, sizeof resolved, path) != ND_OK)
        return ND_ERR_TOOLONG;
    f = fopen(resolved, "wb");
    if (f == NULL)
        return ND_ERR_IO;
    (void)fputs(text, f);
    if (fclose(f) != 0)
        return ND_ERR_IO;
    return ND_OK;
}

nd_err nd_btaudio_asound_text(char *out, size_t n, const char *addr, int card)
{
    if (out == NULL || n == 0u)
        return ND_ERR_INVAL;
    out[0] = '\0';

    if (addr == NULL || addr[0] == '\0') {
        /* The speaker. Deliberately the same shape as the heredoc in
         * /etc/init.d/S17audio: disconnecting has to land on what the boot
         * script would have written, not on something merely similar. */
        return nd_snprintf(out, n,
                           "# Generated by BtAudioService. Edits are overwritten.\n"
                           "pcm.!default {\n"
                           "    type plug\n"
                           "    slave.pcm {\n"
                           "        type hw\n"
                           "        card %d\n"
                           "        device 0\n"
                           "    }\n"
                           "}\n"
                           "\n"
                           "ctl.!default {\n"
                           "    type hw\n"
                           "    card %d\n"
                           "}\n",
                           card, card);
    }

    /* The earbuds. bluealsa exposes one PCM per device per profile and keys
     * it on the address, so the address goes in verbatim -- reformatting it
     * names a PCM that does not exist, and ALSA reports that as a failed open
     * rather than as silence, which is at least honest but is not music.
     *
     * a2dp, not sco: sco is the headset profile, mono and telephone quality.
     * A call may want it later; music never does.
     *
     * No ctl.!default here. bluealsa has no mixer control to point one at, and
     * a ctl aimed at a card that is no longer the default is how amixer ends
     * up adjusting the speaker while you listen to the earbuds.
     *
     * ============ WHY THIS IS WRAPPED IN plug AND THE SPEAKER'S IS TOO ======
     *
     * Everything on this phone that makes a noise is `aplay` on "default", and
     * every one of them asks for the rate and channel count that suits it:
     * Koki's mixer is 22050 Hz MONO, MusicPlayer passes the FILE's own rate
     * and channels, and nd_notify.c hardcodes 44100 stereo. None of them
     * converts, deliberately -- MusicPlayer's header says so outright: "aplay's
     * default device is ALSA's plug layer, whose entire job is rate and channel
     * conversion, so the same conversion happens one layer down". The speaker
     * body above is `type plug` for exactly that reason.
     *
     * This body was not, and a bare bluealsa PCM offers only what the A2DP
     * codec negotiated -- 44100 or 48000, stereo. So a client asking for
     * anything else got -EINVAL out of hw_params and played nothing at all.
     *
     * That is why the fault looked like "Koki has no Bluetooth sound while
     * music does" rather than like a routing bug: 44100 stereo happens to be
     * what A2DP wants, so nd_notify always matched and MusicPlayer matched for
     * any ordinary 44100 stereo file. Koki's 22050 mono could never match, and
     * neither could a music file that was not 44100 stereo.
     *
     * One `plug` fixes all three, and it belongs here rather than in the three
     * callers for the reason the header gives: rewriting this one file moves
     * every sound at once, and there is no per-app audio setting to keep in
     * step. */
    return nd_snprintf(out, n,
                       "# Generated by BtAudioService. Edits are overwritten.\n"
                       "pcm.!default {\n"
                       "    type plug\n"
                       "    slave.pcm {\n"
                       "        type bluealsa\n"
                       "        device \"%s\"\n"
                       "        profile \"a2dp\"\n"
                       "    }\n"
                       "}\n",
                       addr);
}

/* One "Device <addr> <name>" line, or false. `line` is not NUL-terminated at
 * the newline; `len` says where it ends. */
static bool parse_device_line(const char *line, size_t len, nd_btaudio_device *out)
{
    static const char TAG[] = "Device ";
    const size_t tag_len = sizeof TAG - 1u;
    size_t addr_len = 0u;
    size_t i;

    /* bluetoothctl decorates its own output -- "[NEW] Device ...", colour
     * codes, leading spaces -- so the tag is looked for anywhere in the line
     * rather than only at its start. */
    for (i = 0u; i + tag_len <= len; i++) {
        if (memcmp(&line[i], TAG, tag_len) == 0)
            break;
    }
    if (i + tag_len > len)
        return false;
    i += tag_len;

    while (i + addr_len < len && line[i + addr_len] != ' ')
        addr_len++;
    if (addr_len == 0u || addr_len >= sizeof out->addr)
        return false;
    memcpy(out->addr, &line[i], addr_len);
    out->addr[addr_len] = '\0';

    i += addr_len;
    while (i < len && line[i] == ' ')
        i++;

    /* The rest of the line, spaces and all: "Skullcandy Indy ANC" is one name.
     * Splitting on whitespace would put "Skullcandy" in the list and drop the
     * part that tells two pairs of earbuds apart. */
    {
        size_t name_len = len - i;

        if (name_len >= sizeof out->name)
            name_len = sizeof out->name - 1u;
        memcpy(out->name, &line[i], name_len);
        out->name[name_len] = '\0';
    }
    return true;
}

size_t nd_btaudio_parse_devices(const char *text, nd_btaudio_device *out, size_t max)
{
    size_t found = 0u;
    const char *p = text;

    if (text == NULL || out == NULL || max == 0u)
        return 0u;

    while (*p != '\0' && found < max) {
        const char *nl = strchr(p, '\n');
        size_t len = (nl != NULL) ? (size_t)(nl - p) : strlen(p);

        /* A trailing \r from a terminal-ish writer is not part of the name. */
        while (len > 0u && (p[len - 1u] == '\r' || p[len - 1u] == ' '))
            len--;

        if (parse_device_line(p, len, &out[found]))
            found++;
        if (nl == NULL)
            break;
        p = nl + 1;
    }
    return found;
}

bool nd_btaudio_parse_connected(const char *text)
{
    static const char KEY[] = "Connected:";
    const char *p;

    if (text == NULL)
        return false;

    /* The KEY, not the value. "Paired: yes" and "Trusted: yes" sit in the same
     * output, and earbuds in their case are both of those and connected to
     * nothing. */
    p = strstr(text, KEY);
    if (p == NULL)
        return false;
    p += sizeof KEY - 1u;
    while (*p == ' ' || *p == '\t')
        p++;
    return strncmp(p, "yes", 3u) == 0;
}

nd_err nd_btaudio_cmd_build(nd_btaudio_cmd *out, const char *verb, const char *arg, int timeout_s)
{
    size_t n = 0u;

    if (out == NULL || verb == NULL || verb[0] == '\0')
        return ND_ERR_INVAL;

    out->argv[n++] = ND_BTAUDIO_BTCTL;

    /* An agent, for the two verbs that can start an authentication. BlueZ
     * cancels Secure Simple Pairing when no agent is registered anywhere, and
     * a one-shot bluetoothctl registers none unless told to -- which is why
     * pairing here used to end with the earbuds announcing "ready to pair" a
     * second time and a device record carrying no [LinkKey]. */
    if (strcmp(verb, "pair") == 0 || strcmp(verb, "connect") == 0) {
        out->argv[n++] = "--agent";
        out->argv[n++] = ND_BTAUDIO_AGENT;
    }

    /* Absent, not zero. bluetoothctl reads --timeout 0 as "no timeout", so
     * passing it for the verbs that finish by themselves would turn a quick
     * query into a wait with no end. */
    if (timeout_s > 0) {
        if (nd_snprintf(out->seconds, sizeof out->seconds, "%d", timeout_s) != ND_OK)
            return ND_ERR_TOOLONG;
        out->argv[n++] = "--timeout";
        out->argv[n++] = out->seconds;
    } else {
        out->seconds[0] = '\0';
    }

    out->argv[n++] = verb;
    if (arg != NULL && arg[0] != '\0')
        out->argv[n++] = arg;
    out->argv[n] = NULL;
    return ND_OK;
}

/* Whole-file copy through ND_ROOT-resolved paths. Small files only -- an
 * asound.conf is a few hundred bytes and always will be. */
static nd_err copy_conf(const char *from, const char *to)
{
    char text[ND_BTAUDIO_CONF_MAX];
    char resolved[ND_PATH_MAX];
    FILE *f;
    size_t got;

    if (nd_path_resolve(resolved, sizeof resolved, from) != ND_OK)
        return ND_ERR_TOOLONG;
    f = fopen(resolved, "rb");
    if (f == NULL)
        return ND_ERR_NOTFOUND;
    got = fread(text, 1u, sizeof text - 1u, f);
    text[got] = '\0';
    (void)fclose(f);

    return nd_btaudio_write_conf(to, text);
}

nd_err nd_btaudio_route_to(const char *addr, int card)
{
    char text[ND_BTAUDIO_CONF_MAX];
    char resolved[ND_PATH_MAX];
    nd_err rc;

    if (addr != NULL && addr[0] != '\0') {
        /* Save what is there before overwriting it -- but only if nothing is
         * saved yet. Connecting a second device while the first is still the
         * default must not overwrite the SPEAKER route with an earbud one and
         * leave nothing to come back to. */
        if (!nd_path_exists(ND_BTAUDIO_ASOUND_SAVED))
            (void)copy_conf(ND_BTAUDIO_ASOUND, ND_BTAUDIO_ASOUND_SAVED);

        rc = nd_btaudio_asound_text(text, sizeof text, addr, card);
        if (rc != ND_OK)
            return rc;
        return nd_btaudio_write_conf(ND_BTAUDIO_ASOUND, text);
    }

    /* Back to the speaker: the saved bytes if there are any. */
    if (nd_path_exists(ND_BTAUDIO_ASOUND_SAVED)) {
        rc = copy_conf(ND_BTAUDIO_ASOUND_SAVED, ND_BTAUDIO_ASOUND);
        if (rc == ND_OK && nd_path_resolve(resolved, sizeof resolved, ND_BTAUDIO_ASOUND_SAVED) ==
                               ND_OK)
            (void)unlink(resolved);
        if (rc == ND_OK)
            return rc;
        /* fall through: a saved file we could not read is no better than none */
    }

    rc = nd_btaudio_asound_text(text, sizeof text, NULL, card);
    if (rc != ND_OK)
        return rc;
    return nd_btaudio_write_conf(ND_BTAUDIO_ASOUND, text);
}

/* ------------------------------------------------------------------ *
 * The daemons, and running a command
 * ------------------------------------------------------------------ */

#define BTAUDIO_DBUS       "/usr/bin/dbus-daemon"
#define BTAUDIO_BLUETOOTHD "/usr/libexec/bluetooth/bluetoothd"

/* No shared sleep helper exists; nd_remoteshell.c rolls its own for the same
 * reason. These waits are for a daemon to finish coming up, not for a clock. */
static void nap(double seconds)
{
    struct timespec req;

    req.tv_sec = (time_t)seconds;
    req.tv_nsec = (long)((seconds - (double)req.tv_sec) * 1e9);
    (void)nanosleep(&req, NULL);
}

static pid_t g_dbus = -1;
static pid_t g_bluetoothd = -1;
static pid_t g_bluealsa = -1;

/* Spawn with both streams on /dev/null. These three are chatty and their
 * chatter would land in the middle of the serial log during exactly the test
 * that is already hard to read. */
static bool spawn_quiet(const char *path, const char *const *argv, pid_t *pid_out)
{
    nd_proc_spec spec;
    int devnull;
    pid_t pid = -1;

    if (access(path, X_OK) != 0)
        return false;

    devnull = open("/dev/null", O_RDWR | O_CLOEXEC);
    if (devnull < 0)
        return false;

    memset(&spec, 0, sizeof spec);
    spec.argv = argv;
    spec.owner = ND_OWNER_AUDIO; /* long-lived, restarted on failure */
    /* These three outlive the app that starts them, so they must not leave it
     * holding anything. Pointing stdout and stderr at /dev/null is not enough:
     * execve keeps every other inherited descriptor, and the app inherited the
     * pipe nd-core reads it through. Settings would exit, and the core would
     * stay blocked in pipe_read because bluetoothd and bluealsa still held the
     * write end -- the UI froze on leaving Settings, but only once Bluetooth
     * had been used. */
    spec.close_others = true;
    spec.fds[0].child_fd = 1;
    spec.fds[0].our_fd = devnull;
    spec.fds[1].child_fd = 2;
    spec.fds[1].our_fd = devnull;
    spec.n_fds = 2u;

    if (nd_proc_spawn(path, &spec, &pid) != ND_OK) {
        (void)close(devnull);
        return false;
    }
    (void)close(devnull);
    *pid_out = pid;
    return true;
}

static bool still_running(pid_t pid)
{
    return pid > 0 && kill(pid, 0) == 0;
}

nd_err nd_btaudio_daemons_start(void)
{
    /* --system, and its socket lives under /run. bluetoothd talks to nothing
     * else, so a session bus would be a second daemon doing nothing. */
    /* --nopidfile matters more than it looks. dbus-daemon refuses to start
     * when its pid file is already there, and a daemon we killed does not get
     * to remove its own -- so without this, Enable works once per boot and
     * every attempt after it fails with "The pid file exists". */
    static const char *const DBUS_ARGV[] = {BTAUDIO_DBUS, "--system", "--nofork", "--nopidfile",
                                            NULL};
    /* -n keeps it in the foreground so the reaper sees it die; without it
     * bluetoothd forks and the pid we hold is a corpse within a second. */
    static const char *const BTD_ARGV[] = {BTAUDIO_BLUETOOTHD, "-n", NULL};

    /* BlueZ keeps its link keys under /var/lib/bluetooth, one directory per
     * adapter address. That path is read-only squashfs here, so the overlay
     * makes it a symlink onto the user partition and this creates the target.
     *
     * Without it bluetoothd logs "Unable to open adapter storage directory"
     * and every pairing is forgotten the moment the daemon stops -- earbuds
     * would have to be paired afresh every time Bluetooth is switched on,
     * which is not a thing any phone does. */
    (void)nd_mkdir_p("/NeoDCT/User/.bluetooth", 0755u);

    if (!still_running(g_dbus)) {
        (void)nd_mkdir_p("/run/dbus", 0755u);
        if (!spawn_quiet(BTAUDIO_DBUS, DBUS_ARGV, &g_dbus)) {
            nd_log_err(ND_LOG_BTAUDIO, "no dbus-daemon; Bluetooth audio needs it");
            return ND_ERR_NOTFOUND;
        }
        nap(0.6); /* the bus has to be listening before bluetoothd dials it */
    }
    if (!still_running(g_bluetoothd)) {
        if (!spawn_quiet(BTAUDIO_BLUETOOTHD, BTD_ARGV, &g_bluetoothd)) {
            nd_log_err(ND_LOG_BTAUDIO, "no bluetoothd in this build");
            return ND_ERR_NOTFOUND;
        }
        nap(1.2); /* it registers on the bus before bluetoothctl can talk */
    }
    nd_log(ND_LOG_BTAUDIO, "dbus and bluetoothd up");
    return ND_OK;
}

nd_err nd_btaudio_bluealsa_cmd(nd_btaudio_cmd *out)
{
    if (out == NULL)
        return ND_ERR_INVAL;
    out->seconds[0] = '\0';
    out->argv[0] = ND_BTAUDIO_BLUEALSA;
    out->argv[1] = "-p";
    /* SOURCE, and the direction is not the obvious one. bluealsa's -p names
     * the profile THIS device implements, not the peer's. The phone sends the
     * music, so the phone is the A2DP Source and the earbuds are the Sink;
     * registering a2dp-sink here offers the phone as a speaker instead, and a
     * connection to earbuds then finds no complementary profile at either end:
     *
     *   Failed to connect: org.bluez.Error.Failed br-connection-profile-unavailable
     *
     * That error arrives at the moment pairing would, mentions no profile by
     * name, and reads like a pairing failure. It is not one. */
    out->argv[2] = "a2dp-source";
    out->argv[3] = NULL;
    return ND_OK;
}

nd_err nd_btaudio_bluealsa_start(void)
{
    nd_btaudio_cmd cmd;

    if (still_running(g_bluealsa))
        return ND_OK;

    /* bluealsa keeps per-device state -- volume, mostly -- in
     * /var/lib/bluealsa, which is read-only squashfs here. The overlay makes
     * that path a symlink onto the user partition; this creates what it points
     * at. Without it bluealsa warns and forgets the volume of every device
     * between connections, which reads as "the earbuds are quiet again". */
    (void)nd_mkdir_p("/NeoDCT/User/.bluealsa", 0755u);
    if (nd_btaudio_bluealsa_cmd(&cmd) != ND_OK)
        return ND_ERR_INVAL;
    if (!spawn_quiet(ND_BTAUDIO_BLUEALSA, cmd.argv, &g_bluealsa)) {
        nd_log_err(ND_LOG_BTAUDIO, "no bluealsa in this build");
        return ND_ERR_NOTFOUND;
    }
    nap(0.8);
    nd_log(ND_LOG_BTAUDIO, "bluealsa up (a2dp-source)");
    return ND_OK;
}

void nd_btaudio_daemons_stop(int card)
{
    /* The routing first. Killing bluealsa while asound.conf still names it
     * leaves every later open failing on a PCM that no longer exists, which
     * looks like broken audio rather than like Bluetooth being off. */
    (void)nd_btaudio_route_to(NULL, card);

    if (still_running(g_bluealsa))
        (void)nd_proc_terminate(g_bluealsa, 1.0, NULL);
    if (still_running(g_bluetoothd))
        (void)nd_proc_terminate(g_bluetoothd, 1.0, NULL);
    if (still_running(g_dbus))
        (void)nd_proc_terminate(g_dbus, 1.0, NULL);
    g_bluealsa = -1;
    g_bluetoothd = -1;
    g_dbus = -1;
    nd_log(ND_LOG_BTAUDIO, "daemons stopped, sound back on the speaker");
}

int nd_btaudio_run(const nd_btaudio_cmd *cmd, char *capture, size_t cap_n)
{
    nd_proc_spec spec;
    nd_proc_status st;
    pid_t pid = -1;
    int devnull = -1;
    int pipefd[2] = {-1, -1};
    int status = -1;
    size_t used = 0u;

    if (cmd == NULL)
        return -1;
    if (capture != NULL && cap_n > 0u)
        capture[0] = '\0';

    devnull = open("/dev/null", O_RDWR | O_CLOEXEC);
    if (devnull < 0)
        return -1;
    /* O_CLOEXEC on both: the child must not inherit the READ end, or the loop
     * below never sees end-of-file and the Scanning screen never returns. */
    if (pipe2(pipefd, O_CLOEXEC) != 0) {
        (void)close(devnull);
        return -1;
    }

    memset(&spec, 0, sizeof spec);
    spec.argv = cmd->argv;
    spec.owner = ND_OWNER_SYSTEM;
    spec.fds[0].child_fd = 1;
    spec.fds[0].our_fd = pipefd[1];
    spec.fds[1].child_fd = 2;
    spec.fds[1].our_fd = devnull;
    spec.n_fds = 2u;

    if (nd_proc_spawn(cmd->argv[0], &spec, &pid) != ND_OK)
        goto done;

    (void)close(pipefd[1]);
    pipefd[1] = -1;
    for (;;) {
        ssize_t got;

        if (capture == NULL || cap_n == 0u || used + 1u >= cap_n) {
            char sink[256];

            got = read(pipefd[0], sink, sizeof sink);
        } else {
            got = read(pipefd[0], capture + used, cap_n - 1u - used);
            if (got > 0)
                used += (size_t)got;
        }
        if (got < 0 && errno == EINTR)
            continue;
        if (got <= 0)
            break;
    }
    if (capture != NULL && cap_n > 0u)
        capture[used] = '\0';

    memset(&st, 0, sizeof st);
    if (nd_proc_wait(pid, -1.0, &st) == ND_OK)
        status = st.exited ? st.exit_status : 128 + st.signo;

done:
    if (pipefd[0] >= 0)
        (void)close(pipefd[0]);
    if (pipefd[1] >= 0)
        (void)close(pipefd[1]);
    (void)close(devnull);
    return status;
}

bool nd_btaudio_adapter_up(void)
{
    nd_bt_adapter a;

    if (!nd_bt_available())
        return false;
    if (nd_bt_info(0u, &a) != ND_OK)
        return false;
    return (a.flags & ND_BT_FLAG_UP) != 0u;
}
