/* nd_platform.c -- read /NeoDCT/platform once, remember the answer.
 *
 * The whole module is a cache in front of one small file. nd_platform.h has
 * the reasoning for the three-valued answer and for the rule about what
 * UNKNOWN is allowed to decide; this file only has to be careful about two
 * things.
 *
 * The first is that it goes through nd_path_resolve(), so NEODCT_ROOT points
 * it at a fixture and a host test can be a phone for one case without a
 * test-only branch anywhere in the code under test.
 *
 * The second is that it reads the file with nd_props_parse_settings(), the
 * same dialect version.prop and settings.prop are read in (nd_props.h, B-1).
 * That is deliberate rather than convenient: the file is generated by a shell
 * script and read by a shell helper, a C library and, one day, something
 * nobody has written yet, and the fewer parsers exist for one shape the fewer
 * ways they have to disagree. B-1 also answers the awkward cases for free --
 * a truncated or non-UTF-8 file yields an empty map, which lands on UNKNOWN.
 */

#include <stdlib.h>
#include <string.h>

#include "nd_paths.h"
#include "nd_platform.h"
#include "nd_props.h"

static bool g_resolved;
static nd_platform_t g_platform;
static char g_board[ND_PLATFORM_BOARD_MAX];

/* The word -> value mapping, in one place, so the environment override and
 * the file cannot end up understanding different vocabularies. Anything not
 * named here is UNKNOWN, including "luckfox", "arm" and "1" -- a token this
 * build has never heard of is not a token to guess at. */
static nd_platform_t platform_from_word(const char *word)
{
    if (word == NULL)
        return ND_PLATFORM_UNKNOWN;
    if (strcmp(word, ND_PLATFORM_NAME_HW) == 0)
        return ND_PLATFORM_HW;
    if (strcmp(word, ND_PLATFORM_NAME_QEMU) == 0)
        return ND_PLATFORM_QEMU;
    return ND_PLATFORM_UNKNOWN;
}

/* ============ g_resolved IS SET LAST, AND THAT IS THE WHOLE ORDER ========
 *
 * It used to be set on the first line, before either answer was written, and
 * that is a lie visible from another thread: the crash reporter and the modem
 * thread both ask nd_platform(), and one arriving in the window between the
 * flag and the values sees `resolved` with a freshly-zeroed g_platform --
 * ND_PLATFORM_UNKNOWN -- and prints "unknown (this image carries no
 * /NeoDCT/platform)" about a phone that carries one. A crash report that
 * misidentifies the hardware is worse than one that says nothing, because it
 * is believed.
 *
 * Written last, the worst a lost race can do is have two threads parse the
 * same small file and write the same values, which costs one redundant read
 * and is otherwise invisible. That is the trade this module can make and a
 * lock is not: nd_platform() is called from signal-adjacent paths (the crash
 * handler is one) where taking a mutex is the thing that must not happen.
 *
 * The early returns are gone for the same reason -- there is one exit and the
 * flag is on it -- rather than because the branches wanted rearranging. */
static void resolve(void)
{
    const char *env;

    g_platform = ND_PLATFORM_UNKNOWN;
    g_board[0] = '\0';

    /* 1. The environment, when it says something. It wins over the file so
     *    that a developer can put a phone's answer in front of code running
     *    on a laptop; it carries no board, for the reason in the header. */
    env = getenv(ND_ENV_PLATFORM);
    if (env != NULL && env[0] != '\0') {
        g_platform = platform_from_word(env);
    } else {
        /* 2. The image's own record. A NULL here is an allocation failure:
         *    UNKNOWN, and nothing else to say. */
        nd_props *p = nd_props_parse_settings(ND_PATH_PLATFORM);

        if (p != NULL) {
            g_platform = platform_from_word(nd_props_get(p, ND_PLATFORM_KEY_PLATFORM, NULL));

            /* The board is read only once the platform word parsed. A record
             * whose first key we did not understand is not a record to quote
             * the second key out of -- a caller that acted on board= while the
             * platform was UNKNOWN would be making exactly the claim UNKNOWN
             * exists to withhold. */
            if (g_platform != ND_PLATFORM_UNKNOWN) {
                (void)nd_strlcpy(g_board, nd_props_get(p, ND_PLATFORM_KEY_BOARD, ""),
                                 sizeof g_board);
            }
            nd_props_free(p);
        }
    }

    g_resolved = true; /* LAST. See the note above. */
}

nd_platform_t nd_platform(void)
{
    if (!g_resolved)
        resolve();
    return g_platform;
}

const char *nd_platform_name(void)
{
    switch (nd_platform()) {
    case ND_PLATFORM_QEMU:
        return ND_PLATFORM_NAME_QEMU;
    case ND_PLATFORM_HW:
        return ND_PLATFORM_NAME_HW;
    case ND_PLATFORM_UNKNOWN:
    default:
        return ND_PLATFORM_NAME_UNKNOWN;
    }
}

const char *nd_platform_board(void)
{
    (void)nd_platform();
    return g_board;
}

bool nd_platform_is_hw(void)
{
    return nd_platform() == ND_PLATFORM_HW;
}

bool nd_platform_is_qemu(void)
{
    return nd_platform() == ND_PLATFORM_QEMU;
}

void nd_platform__reset_cache(void)
{
    g_resolved = false;
    g_platform = ND_PLATFORM_UNKNOWN;
    g_board[0] = '\0';
}
