DIR_TEST_ITEMS := fbformat:fbformat.c text-speed:text-speed.c plottest:plottest.c bitmap:bitmap.c;nsglobe.c frontend:frontend.c bezier:bezier.c path:path.c polygon:polygon.c polystar:polystar.c polystar2:polystar2.c evdev:evdev.c

include $(NSBUILD)/Makefile.subdir
