#!/bin/sh
# Write the image's identity into /NeoDCT/System/version.prop and create the
# mountpoints the immutable layout needs.
#
# version.prop lives inside the read-only rootfs, so a system update replaces
# it wholesale. That is the point: /NeoDCT/User/settings.prop is on its own
# partition and survives an update, so it must not be where the version is
# recorded or the phone would report its factory version forever.
#
# The version itself comes from /etc/os-release (VERSION_ID) so the overlay
# stays the single place a release number gets bumped.
#
# Usage: post-build-system-metadata.sh TARGET_DIR [...] PLATFORM
#
# Buildroot calls post-build scripts as
#
#   script TARGET_DIR $BR2_ROOTFS_POST_SCRIPT_ARGS $BR2_ROOTFS_POST_BUILD_SCRIPT_ARGS
#
# and the qemu board's post-image script needs the defconfig path in
# POST_SCRIPT_ARGS, so that path arrives in $2 and the platform is last.
# Reading $2 wrote a build-machine path into system.os.platform, which is the
# value every update's manifest is checked against -- an update built in a
# different directory would have been refused as the wrong hardware.
set -eu

TARGET_DIR="${1:-}"
if [ -z "$TARGET_DIR" ] || [ ! -d "$TARGET_DIR" ]; then
    echo "[post-build] Missing TARGET_DIR" >&2
    exit 1
fi
shift

PLATFORM="unknown"
for argument in "$@"; do
    PLATFORM="$argument"
done
case "$PLATFORM" in
    # A path is somebody else's argument, not a platform id: the value has to
    # mean the same thing on every machine that ever builds this.
    ""|*/*) PLATFORM="unknown" ;;
esac

OS_RELEASE="$TARGET_DIR/etc/os-release"
VERSION=""
if [ -r "$OS_RELEASE" ]; then
    VERSION="$(sed -n 's/^VERSION_ID=//p' "$OS_RELEASE" | tr -d '"' | head -n1)"
fi
if [ -z "$VERSION" ]; then
    echo "[post-build] No VERSION_ID in $OS_RELEASE" >&2
    exit 1
fi

# Reproducible builds set SOURCE_DATE_EPOCH; honour it when present.
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
    EPOCH="$SOURCE_DATE_EPOCH"
else
    EPOCH="$(date -u '+%s')"
fi
BUILD_TIME="$(date -u -d "@$EPOCH" '+%Y-%m-%d %H:%M UTC' 2>/dev/null || \
    date -u -r "$EPOCH" '+%Y-%m-%d %H:%M UTC' 2>/dev/null || \
    date -u '+%Y-%m-%d %H:%M UTC')"

SYSTEM_DIR="$TARGET_DIR/NeoDCT/System"
mkdir -p "$SYSTEM_DIR"
cat > "$SYSTEM_DIR/version.prop" <<EOF
# Generated by post-build-system-metadata.sh -- do not edit.
# Facts about this image. User settings are in /NeoDCT/User/settings.prop.
system.os.versionnumber=$VERSION
system.os.versionname=NeoDCT System v$VERSION
system.os.platform=$PLATFORM
system.os.buildtime=$BUILD_TIME
system.os.buildepoch=$EPOCH
EOF

# Mountpoints must exist inside the read-only rootfs -- nothing can create
# them at runtime. /NeoDCT/User is where the user-data partition lands; the
# sdcard mountpoint is made on that partition at boot by S00userdata.
mkdir -p "$TARGET_DIR/NeoDCT/User"

echo "[post-build] $PLATFORM v$VERSION ($BUILD_TIME)"

# --- boot banner ----------------------------------------------------------
# Rendered here, on the build host, rather than on the phone: figlet is a
# build-time convenience and has no business in a 64MB image. The version
# comes from the same VERSION_ID as everything else, so the banner cannot
# drift from what the phone actually is -- which is exactly what happened
# to the login issue string, still advertising 0.3.0a several releases on.
#
# No figlet on the build host is not an error. The banner falls back to
# plain text and the boot looks slightly duller.
BANNER="$TARGET_DIR/etc/neodct-banner"
BANNER_TEXT="NeoDCT OS $VERSION"
if command -v figlet > /dev/null 2>&1; then
    # "small" is 66 columns for this string -- fits an 80-column console
    # with room to spare. "standard" is 77 and wraps on anything narrower.
    figlet -f small "$BANNER_TEXT" > "$BANNER" 2>/dev/null \
        || printf '%s\n' "$BANNER_TEXT" > "$BANNER"
else
    printf '%s\n' "$BANNER_TEXT" > "$BANNER"
fi
echo "[post-build] boot banner: $BANNER_TEXT"

# /etc/issue too. BR2_TARGET_GENERIC_ISSUE is a literal string in the
# defconfig, so it says whatever it said when someone last remembered to
# edit it -- it was still advertising 0.3.0a at 0.3.5a. Rewrite it from
# VERSION_ID like everything else here.
printf 'NeoDCT System v%s\n' "$VERSION" > "$TARGET_DIR/etc/issue"
