#!/bin/sh
# Write the image's identity into /NeoDCT/System/version.prop and create the
# mountpoints the immutable layout needs.
#
# version.prop lives inside the read-only rootfs, so a system update replaces
# it wholesale. That is the point: /NeoDCT/User/settings.prop is on its own
# partition and survives an update, so it must not be where the version is
# recorded or the phone would report its factory version forever.
#
# The version itself comes from /etc/os-release (VERSION_ID) so the overlay
# stays the single place a release number gets bumped.
#
# Usage: post-build-system-metadata.sh TARGET_DIR [...] PLATFORM
#
# Buildroot calls post-build scripts as
#
#   script TARGET_DIR $BR2_ROOTFS_POST_SCRIPT_ARGS $BR2_ROOTFS_POST_BUILD_SCRIPT_ARGS
#
# and the qemu board's post-image script needs the defconfig path in
# POST_SCRIPT_ARGS, so that path arrives in $2 and the platform is last.
# Reading $2 wrote a build-machine path into system.os.platform, which is the
# value every update's manifest is checked against -- an update built in a
# different directory would have been refused as the wrong hardware.
set -eu

TARGET_DIR="${1:-}"
if [ -z "$TARGET_DIR" ] || [ ! -d "$TARGET_DIR" ]; then
    echo "[post-build] Missing TARGET_DIR" >&2
    exit 1
fi
shift

PLATFORM="unknown"
for argument in "$@"; do
    PLATFORM="$argument"
done
case "$PLATFORM" in
    # A path is somebody else's argument, not a platform id: the value has to
    # mean the same thing on every machine that ever builds this.
    ""|*/*) PLATFORM="unknown" ;;
esac

# ============ AND THE SAME FACT IN THE SHAPE A BOOT SCRIPT CAN READ ========
#
# system.os.platform above is the UPDATE system's compatibility key: an
# .ndsw's manifest is checked against it (nd_manifest_check_compatible), and
# the release asset is named from it (nd_remote_asset_name). Its format is
# load-bearing for every package ever built, so it is not touched here.
#
# What it cannot be is the thing that answers "am I on the phone?". Reading it
# from C goes through nd_settings_get(), and nd_settings.h's R-24 quirk makes
# every read of a key outside DEFAULTS rewrite settings.prop with an fsync --
# real flash wear on UBIFS, from a question a crash handler and a boot script
# want to ask. And nothing in busybox sh parses version.prop at all -- its
# build time is a date with spaces and a colon in it, and /bin/nd-platform
# hands on only values made of [A-Za-z0-9._-], so it would throw that value
# away rather than pass it to a caller.
#
# So: a sibling, derived from the same $PLATFORM so the two can never
# disagree, in the props shape the rest of the tree already parses.
#
# The board is split out from the platform on purpose. A future dev-kit board
# ships as platform=hw board=devkit-x and every existing "is this hardware"
# branch keeps working; a third value of a single word would have broken all
# of them at once.
case "$PLATFORM" in
    qemu-aarch64)  FLAG_PLATFORM="qemu"; FLAG_BOARD="qemu-virt" ;;
    luckfox-armv7) FLAG_PLATFORM="hw";   FLAG_BOARD="luckfox-pico-mini-b" ;;
    *)             FLAG_PLATFORM="unknown"; FLAG_BOARD="" ;;
esac

# And an unknown platform stops the build, exactly as a missing VERSION_ID
# does below.
#
# The alternative is to ship platform=unknown, and post-build-prune-tests.sh
# is the record of what that costs: the same last-argument mistake made
# "${PLATFORM%%-*}" = "luckfox" silently false, and real hardware shipped the
# generic inittab for several releases with nothing in the build saying so. A
# post-build script that falls through quietly produces an image that looks
# finished and is not. It is also already true that system.os.platform=unknown
# is an image no update can ever be built for, so there is nothing here worth
# rescuing.
if [ "$FLAG_PLATFORM" = "unknown" ]; then
    echo "[post-build] Unknown platform id \"$PLATFORM\"" >&2
    echo "[post-build]   expected the last argument to be qemu-aarch64 or" >&2
    echo "[post-build]   luckfox-armv7 -- see BR2_ROOTFS_POST_BUILD_SCRIPT_ARGS" >&2
    echo "[post-build]   in the defconfig. Refusing to write /NeoDCT/platform" >&2
    echo "[post-build]   with nothing in it: see this script's own comment." >&2
    exit 1
fi

OS_RELEASE="$TARGET_DIR/etc/os-release"
VERSION=""
if [ -r "$OS_RELEASE" ]; then
    VERSION="$(sed -n 's/^VERSION_ID=//p' "$OS_RELEASE" | tr -d '"' | head -n1)"
fi
if [ -z "$VERSION" ]; then
    echo "[post-build] No VERSION_ID in $OS_RELEASE" >&2
    exit 1
fi

# Reproducible builds set SOURCE_DATE_EPOCH; honour it when present.
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
    EPOCH="$SOURCE_DATE_EPOCH"
else
    EPOCH="$(date -u '+%s')"
fi
BUILD_TIME="$(date -u -d "@$EPOCH" '+%Y-%m-%d %H:%M UTC' 2>/dev/null || \
    date -u -r "$EPOCH" '+%Y-%m-%d %H:%M UTC' 2>/dev/null || \
    date -u '+%Y-%m-%d %H:%M UTC')"

SYSTEM_DIR="$TARGET_DIR/NeoDCT/System"
mkdir -p "$SYSTEM_DIR"
cat > "$SYSTEM_DIR/version.prop" <<EOF
# Generated by post-build-system-metadata.sh -- do not edit.
# Facts about this image. User settings are in /NeoDCT/User/settings.prop.
system.os.versionnumber=$VERSION
system.os.versionname=NeoDCT System v$VERSION
system.os.platform=$PLATFORM
system.os.buildtime=$BUILD_TIME
system.os.buildepoch=$EPOCH
EOF

# The flag itself: four lines, one short token per value, one directory up
# from version.prop. Read in C through nd_platform.h, in shell through
# /bin/nd-platform, and never by sourcing it -- AGENTS.md's rule is that a
# record is parsed with `while IFS= read`, so a value can never execute.
#
# ============ AND WHERE IT IS NOT AVAILABLE ============
#
# THE INITRAMFS CANNOT READ THIS FILE. It is in the root squashfs, and the
# initramfs runs before that is mounted; mkinitramfs.py packs busybox,
# dmsetup, nd-verify, the release key and the init scripts, and not this.
#
# That is settled rather than pending, and it is worth writing down because
# "the boot needs it, so surely the initramfs does" is the obvious next
# thought. Two reasons it is wrong. Nothing in neodct/initramfs/ asks which
# machine it is on: every decision there is made from the evidence in front of
# it -- is /dev/fb0 a character device, did the panel daemon exit on its own,
# what does neodct.sys= say -- and that is the "did this device enumerate"
# question nd_platform.h says explicitly not to route through here. And a copy
# in the cpio would be a SECOND copy of the fact with its own lifetime: no
# .ndsw carries a kernel, and on the phone the initramfs is built into one, so
# the copy would freeze at flash time and drift from the rootfs it exists to
# agree with. One file, one writer, one reader path.
cat > "$TARGET_DIR/NeoDCT/platform" <<EOF
# Generated by post-build-system-metadata.sh -- do not edit.
platform=$FLAG_PLATFORM
board=$FLAG_BOARD
image=$PLATFORM
EOF

# Mountpoints must exist inside the read-only rootfs -- nothing can create
# them at runtime. /NeoDCT/User is where the user-data partition lands; the
# sdcard mountpoint is made on that partition at boot by S00userdata.
mkdir -p "$TARGET_DIR/NeoDCT/User"

echo "[post-build] $PLATFORM v$VERSION ($BUILD_TIME)"
echo "[post-build] /NeoDCT/platform: platform=$FLAG_PLATFORM board=$FLAG_BOARD"

# --- boot banner ----------------------------------------------------------
# Rendered here, on the build host, rather than on the phone: figlet is a
# build-time convenience and has no business in a 64MB image. The version
# comes from the same VERSION_ID as everything else, so the banner cannot
# drift from what the phone actually is -- which is exactly what happened
# to the login issue string, still advertising 0.3.0a several releases on.
#
# No figlet on the build host is not an error. The banner falls back to
# plain text and the boot looks slightly duller.
BANNER="$TARGET_DIR/etc/neodct-banner"
BANNER_TEXT="NeoDCT OS $VERSION"
if command -v figlet > /dev/null 2>&1; then
    # "small" is 66 columns for this string -- fits an 80-column console
    # with room to spare. "standard" is 77 and wraps on anything narrower.
    figlet -f small "$BANNER_TEXT" > "$BANNER" 2>/dev/null \
        || printf '%s\n' "$BANNER_TEXT" > "$BANNER"
else
    printf '%s\n' "$BANNER_TEXT" > "$BANNER"
fi
echo "[post-build] boot banner: $BANNER_TEXT"

# /etc/issue too. BR2_TARGET_GENERIC_ISSUE is a literal string in the
# defconfig, so it says whatever it said when someone last remembered to
# edit it -- it was still advertising 0.3.0a at 0.3.5a. Rewrite it from
# VERSION_ID like everything else here.
printf 'NeoDCT System v%s\n' "$VERSION" > "$TARGET_DIR/etc/issue"
