"""/bin/nd-platform -- the same answer as nd_platform(), for busybox sh.

The init scripts cannot link libneodct, so S10udevd and S90display ask this
instead. It has to agree with the C on all three values, because the two are
deciding the same things about the same boot: whether to wait 600 ms for the
modem's ttyUSB nodes, and whether to start the panel daemon.

The value it must get right is the third one. A missing or unreadable
/NeoDCT/platform is "unknown", which is a real answer and not a synonym for
either of the others -- nd_platform.h has the reasoning, and the short version
is that defaulting to hw arms hardware waits on a dev box and defaulting to
qemu is the 0.5.9a regression class in reverse. So `is hw` and `is qemu` are
separate, both fail under unknown, and there is deliberately no negation form
for anybody to reach for.

The file is PARSED and never sourced (AGENTS.md), and the value charset is
narrower than the file format allows, so a value that is not a plain lowercase
token is a file this script does not understand rather than one to hand on to
a caller. That last one is asserted here with a value that would be a command
if anything ever sourced it.
"""

import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HELPER = os.path.join(ROOT, "overlay", "bin", "nd-platform")

HW_RECORD = ("# Generated by post-build-system-metadata.sh -- do not edit.\n"
             "platform=hw\n"
             "board=luckfox-pico-mini-b\n"
             "image=luckfox-armv7\n")

QEMU_RECORD = ("# Generated by post-build-system-metadata.sh -- do not edit.\n"
               "platform=qemu\n"
               "board=qemu-virt\n"
               "image=qemu-aarch64\n")


def run(tmp_path, *args, record=None, env_platform=None, path=None):
    """Drive the shipped script with NEODCT_PLATFORM_FILE pointed at a fixture.

    `record=None` means no file at all, which is the case that matters most.
    """
    flag = tmp_path / "platform"
    if record is not None:
        flag.write_text(record)
    env = dict(os.environ, NEODCT_PLATFORM_FILE=str(path if path else flag))
    env.pop("NEODCT_PLATFORM", None)
    if env_platform is not None:
        env["NEODCT_PLATFORM"] = env_platform
    return subprocess.run(["sh", HELPER] + list(args),
                          capture_output=True, text=True, env=env)


# --- the bare form: the word, and never an empty one ------------------------

def test_the_word_is_hw_on_a_hardware_image(tmp_path):
    result = run(tmp_path, record=HW_RECORD)

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "hw"


def test_the_word_is_qemu_on_a_qemu_image(tmp_path):
    result = run(tmp_path, record=QEMU_RECORD)

    assert result.stdout.strip() == "qemu"


def test_no_file_at_all_is_unknown(tmp_path):
    """THE CENTRAL CASE. Not hw, not qemu, and never empty."""
    result = run(tmp_path, record=None)

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "unknown"


def test_a_word_this_script_has_never_heard_of_is_unknown(tmp_path):
    result = run(tmp_path, record="platform=luckfox\n")

    assert result.stdout.strip() == "unknown"


# --- `is`: the two predicates, and no third ---------------------------------

def test_is_hw_succeeds_only_on_hardware(tmp_path):
    assert run(tmp_path, "is", "hw", record=HW_RECORD).returncode == 0
    assert run(tmp_path, "is", "hw", record=QEMU_RECORD).returncode == 1


def test_is_qemu_succeeds_only_on_the_emulator(tmp_path):
    assert run(tmp_path, "is", "qemu", record=QEMU_RECORD).returncode == 0
    assert run(tmp_path, "is", "qemu", record=HW_RECORD).returncode == 1


def test_both_predicates_fail_when_there_is_no_record(tmp_path):
    """The property S10udevd and S90display are built on: an image that cannot
    say is not an image that gets told it has a modem to wait for."""
    assert run(tmp_path, "is", "hw", record=None).returncode == 1
    assert run(tmp_path, "is", "qemu", record=None).returncode == 1


def test_is_refuses_a_word_that_is_not_one_of_the_two(tmp_path):
    """`is unknown` is deliberately not a thing: the exit status is for the
    two truth questions, and "did the record parse" is not one of them."""
    result = run(tmp_path, "is", "unknown", record=HW_RECORD)

    assert result.returncode == 2
    assert "usage" in result.stderr


# --- `get`: any key, and nothing invented ------------------------------------

def test_get_reads_the_other_keys(tmp_path):
    assert run(tmp_path, "get", "board",
               record=HW_RECORD).stdout.strip() == "luckfox-pico-mini-b"
    assert run(tmp_path, "get", "image",
               record=HW_RECORD).stdout.strip() == "luckfox-armv7"


def test_get_reports_an_absent_key_rather_than_printing_nothing_quietly(tmp_path):
    result = run(tmp_path, "get", "serial", record=HW_RECORD)

    assert result.returncode == 1
    assert result.stdout == ""


def test_get_on_a_missing_file_fails(tmp_path):
    result = run(tmp_path, "get", "board", record=None)

    assert result.returncode == 1
    assert result.stdout == ""


# --- the environment override, as in the C ----------------------------------

def test_the_environment_beats_the_file(tmp_path):
    result = run(tmp_path, record=HW_RECORD, env_platform="qemu")

    assert result.stdout.strip() == "qemu"
    assert run(tmp_path, "is", "qemu", record=HW_RECORD,
               env_platform="qemu").returncode == 0


def test_the_environment_carries_no_board(tmp_path):
    """A board is a claim about a piece of hardware and an environment
    variable is not evidence of one -- so `get board` still reads the file."""
    result = run(tmp_path, "get", "board", record=QEMU_RECORD, env_platform="hw")

    assert result.stdout.strip() == "qemu-virt"


def test_an_override_this_script_does_not_know_is_unknown(tmp_path):
    """And it does NOT fall through to the file: a typo must not silently
    mean "believe the image", which is the opposite of what setting the
    variable asked for."""
    result = run(tmp_path, record=HW_RECORD, env_platform="hardware")

    assert result.stdout.strip() == "unknown"


# --- the file is data, not script -------------------------------------------

def test_a_value_with_shell_metacharacters_is_rejected_not_passed_on(tmp_path):
    """AGENTS.md: a record is parsed, never sourced, so a value can never
    execute. The charset guard is the second half of that -- a value this file
    cannot legitimately carry is a file we do not understand, not a string to
    hand to whatever called `get`."""
    marker = tmp_path / "ran"
    record = ("platform=hw\n"
              "board=$(touch %s)\n"
              "image=a;b|c `d`\n" % marker)

    board = run(tmp_path, "get", "board", record=record)
    image = run(tmp_path, "get", "image", record=record)

    assert board.returncode == 1 and board.stdout == ""
    assert image.returncode == 1 and image.stdout == ""
    assert not marker.exists()
    # And the platform word beside them still reads normally: one unusable
    # value is not a reason to throw the whole record away.
    assert run(tmp_path, record=record).stdout.strip() == "hw"


def test_a_poisoned_platform_value_is_unknown_and_does_not_run(tmp_path):
    marker = tmp_path / "ran"
    record = "platform=`touch %s`hw\n" % marker

    result = run(tmp_path, record=record)

    assert result.stdout.strip() == "unknown"
    assert not marker.exists()


def test_a_comment_line_is_not_mistaken_for_a_key(tmp_path):
    """The first line of every generated record is a comment with no '=' in
    it, so it simply never matches a key."""
    result = run(tmp_path, "get", "platform", record=HW_RECORD)

    assert result.stdout.strip() == "hw"


# --- the file the phone actually reads --------------------------------------

def test_a_last_line_with_no_newline_is_still_read(tmp_path):
    """`read` returns non-zero on a final unterminated line even though it has
    filled the variables, so the naive loop drops it. The generated record
    always ends in a newline, which is exactly why this would have gone
    unnoticed until something wrote one that did not."""
    record = "platform=hw\nboard=luckfox-pico-mini-b\nimage=luckfox-armv7"

    assert run(tmp_path, "get", "image",
               record=record).stdout.strip() == "luckfox-armv7"


def test_a_record_that_is_only_an_unterminated_line_still_parses(tmp_path):
    result = run(tmp_path, record="platform=qemu")

    assert result.stdout.strip() == "qemu"


def test_the_default_file_is_the_absolute_runtime_path():
    """NEODCT_PLATFORM_FILE is the tests' hook and nothing else: the shipped
    default has to be the real path, or the boot scripts read nothing."""
    source = open(HELPER).read()

    assert ': "${NEODCT_PLATFORM_FILE:=/NeoDCT/platform}"' in source


def test_the_helper_is_shipped_executable_at_the_path_its_callers_use():
    """The rootfs is a read-only squashfs assembled from the overlay, so
    overlay/bin/nd-platform IS /bin/nd-platform and nothing can chmod it at
    runtime. Both init scripts call it by absolute path with no `command -v`
    guard -- S10udevd would silently stop waiting for the modem's ports and
    S90display would silently stop starting the panel daemon."""
    assert os.access(HELPER, os.X_OK), "overlay/bin/nd-platform is not executable"
    assert open(HELPER).readline().startswith("#!/bin/sh")

    initd = os.path.join(ROOT, "overlay", "etc", "init.d")
    for name in ("S10udevd", "S90display"):
        body = open(os.path.join(initd, name)).read()
        assert "/bin/nd-platform" in body, name


def test_the_helper_never_sources_the_record():
    """The one line that would turn a record into a program."""
    source = open(HELPER).read()
    body = [line.strip() for line in source.splitlines()
            if not line.strip().startswith("#")]

    assert not [line for line in body
                if line.startswith(". ") or line.startswith("source ")]
    assert "while IFS='=' read -r" in source
