/* test_remote.c -- finding and fetching an update over the network, on a
 * machine that has no network.
 *
 * ============ WHAT IS AND IS NOT BEING TESTED ============
 *
 * NO BUILD OF nd_remote.c HAS EVER SPOKEN TO GITHUB. Not here, not by hand,
 * not once -- and nothing below claims otherwise. What is exercised is
 * everything up to and including the process boundary: the argv nd_remote.c
 * builds, the three pipes it opens, the header parsing, the status
 * classification, the resume arithmetic, the backoff, and the bytes that
 * end up on the card.
 *
 * The way that is arranged is the same trick the Koki audio work used for
 * aplay: a stand-in `curl` is put first on PATH. nd_remote.c finds it with
 * its own PATH walk, spawns it with nd_proc_spawn(), and cannot tell the
 * difference. NOTHING in the library is compiled differently, stubbed, or
 * given a test-only branch -- the only seam is nd_remote_set_sleep_fn(),
 * which exists so that a backoff of 5 + 10 + 20 seconds does not have to be
 * waited out, and it is the seam spec-update-system.md asked for.
 *
 * The stand-in is neodct/tests/remote/fake-curl and it serves COMMITTED
 * fixture files: real GitHub-shaped JSON, and a 4000-byte package whose
 * bytes are a known pattern, so a download that is reassembled wrongly
 * shows up as a wrong byte and not merely as a wrong length.
 *
 * ============ WHAT WAS ESTABLISHED WITH THE REAL curl, BY HAND ============
 *
 * Four things, against curl 8.5.0, outside this file:
 *
 *   - the exact argv is accepted. Every option, in the order the library
 *     writes them, exits with a transfer code and never exit 2 ("option
 *     unknown").
 *   - -D /proc/self/fd/3 works on a pipe, and curl FLUSHES the header block
 *     before it writes any body: with the body throttled to nine seconds,
 *     the header write landed at 15 ms. That measurement is why the poll
 *     loop can read the status before the bytes it describes.
 *   - -H "Range: bytes=N-" survives a 302 to another host, and the second
 *     response is a 206.
 *   - --proto '=https' really does refuse an http URL, exit 1.
 *
 * ============ WHAT NOTHING HAS SHOWN ============
 *
 *   - that GitHub answers the way the fixtures do. The one attempt to ask
 *     it reached a proxy, which answered 403 on GitHub's behalf; api.github
 *     .com itself has never replied to this argv. It did teach the CONNECT
 *     lesson below.
 *   - that TLS verifies against the phone's own CA bundle.
 *   - that a 53 MB transfer over a carrier behaves like a 4000-byte one.
 *   - anything at all about the phone's bearer.
 *
 * ============ THE PYTHON IS THE ORACLE FOR ORDERING ============
 *
 * version_order.txt is 625 candidate/installed pairs and the answer
 * System/core/UpdateService/remote.py's is_newer() actually gave for each,
 * generated by running it. Every one is checked here. is_newer is where an
 * off-by-one silently offers a downgrade as an upgrade, so "looks right to
 * me" is not enough for it.
 */

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "nd_paths.h"
#include "nd_remote.h"
#include "nd_types.h"
#include "nd_update.h"

static int g_checks;
static int g_fail;

#define CHECK(cond, what)                                                          \
    do {                                                                           \
        g_checks++;                                                                \
        if (!(cond)) {                                                             \
            g_fail++;                                                              \
            (void)fprintf(stderr, "FAIL %s:%d  %s\n", __FILE__, __LINE__, (what)); \
        }                                                                          \
    } while (0)

#define CHECK_INT(got, want, what)                                                            \
    do {                                                                                      \
        long long g_ = (long long)(got);                                                      \
        long long w_ = (long long)(want);                                                     \
        g_checks++;                                                                           \
        if (g_ != w_) {                                                                       \
            g_fail++;                                                                         \
            (void)fprintf(stderr, "FAIL %s:%d  %s: got %lld want %lld\n", __FILE__, __LINE__, \
                          (what), g_, w_);                                                    \
        }                                                                                     \
    } while (0)

#define CHECK_STR(got, want, what)                                                                \
    do {                                                                                          \
        const char *g_ = (got);                                                                   \
        const char *w_ = (want);                                                                  \
        g_checks++;                                                                               \
        if (g_ == NULL || strcmp(g_, w_) != 0) {                                                  \
            g_fail++;                                                                             \
            (void)fprintf(stderr, "FAIL %s:%d  %s: got \"%s\" want \"%s\"\n", __FILE__, __LINE__, \
                          (what), g_ != NULL ? g_ : "(null)", w_);                                \
        }                                                                                         \
    } while (0)

/* ------------------------------------------------------------------ *
 * Where things live
 * ------------------------------------------------------------------ */

static char g_fixtures[ND_PATH_MAX]; /* neodct/tests/remote          */
static char g_sandbox[ND_PATH_MAX];  /* a scratch ND_ROOT            */
static char g_ctl[ND_PATH_MAX];      /* the stand-in's control files */
static char g_bindir[ND_PATH_MAX];   /* holds our `curl`             */
static char g_path_keep[ND_PATH_MAX * 2];

/* The fixtures sit beside the source tree and not under a phone root, so
 * this walks up from the test binary the way test_signing.c does. */
static bool find_fixtures(void)
{
    char self[ND_PATH_MAX];
    ssize_t n = readlink("/proc/self/exe", self, sizeof self - 1u);
    char *slash;

    if (n <= 0)
        return false;
    self[n] = '\0';
    slash = strrchr(self, '/');
    if (slash == NULL)
        return false;
    *slash = '\0';
    /* build/<variant>/test -> ../../../../tests/remote */
    return nd_snprintf(g_fixtures, sizeof g_fixtures, "%s/../../../../tests/remote", self) == ND_OK;
}

static const char *fixture(const char *name)
{
    static char slots[4][ND_PATH_MAX];
    static unsigned next;
    char *p = slots[next % 4u];

    next++;
    if (nd_snprintf(p, ND_PATH_MAX, "%s/%s", g_fixtures, name) != ND_OK)
        return NULL;
    return p;
}

static bool run(const char *fmt, ...) ND_PRINTF(1, 2);

static bool run(const char *fmt, ...)
{
    char cmd[ND_PATH_MAX * 3];
    va_list ap;
    int n;

    va_start(ap, fmt);
    n = vsnprintf(cmd, sizeof cmd, fmt, ap);
    va_end(ap);
    if (n < 0 || (size_t)n >= sizeof cmd)
        return false;
    return system(cmd) == 0;
}

/* ------------------------------------------------------------------ *
 * The stand-in curl, and the scenario it serves
 * ------------------------------------------------------------------ */

static bool sandbox_up(void)
{
    const char *base = getenv("TMPDIR");

    if (base == NULL || base[0] == '\0')
        base = "/tmp";
    if (nd_snprintf(g_sandbox, sizeof g_sandbox, "%s/ndremote-XXXXXX", base) != ND_OK)
        return false;
    if (mkdtemp(g_sandbox) == NULL)
        return false;
    if (nd_snprintf(g_ctl, sizeof g_ctl, "%s/ctl", g_sandbox) != ND_OK ||
        nd_snprintf(g_bindir, sizeof g_bindir, "%s/bin", g_sandbox) != ND_OK)
        return false;
    if (mkdir(g_ctl, 0755) != 0 || mkdir(g_bindir, 0755) != 0)
        return false;
    if (!run("mkdir -p '%s/dl'", g_sandbox))
        return false;

    /* Every virtual path below ("/dl/UPDATE.ndsw") lands inside the
     * sandbox, so nothing this test writes can reach a real /NeoDCT. */
    return nd_path_set_root(g_sandbox) == ND_OK;
}

/* Put the stand-in first on PATH. Split from the copy because
 * test_no_curl_at_all() empties PATH, and everything here -- including
 * system() -- needs it back afterwards without shelling out to do it. */
static bool path_with_fake_curl(void)
{
    char path[ND_PATH_MAX * 2];

    if (nd_snprintf(path, sizeof path, "%s:%s", g_bindir, g_path_keep) != ND_OK)
        return false;
    return setenv("PATH", path, 1) == 0;
}

static bool fake_curl_install(void)
{
    const char *old = getenv("PATH");

    (void)nd_strlcpy(g_path_keep, (old != NULL) ? old : "/usr/bin:/bin", sizeof g_path_keep);
    if (!run("cp '%s' '%s/curl' && chmod 0755 '%s/curl'", fixture("fake-curl"), g_bindir, g_bindir))
        return false;
    return path_with_fake_curl() && setenv("NDCURL_DIR", g_ctl, 1) == 0;
}

/* Wipe the scenario, including the call log. Every test starts clean. */
static void scenario_reset(void)
{
    (void)run("rm -f '%s'/*", g_ctl);
}

static void ctl_set(const char *name, const char *value)
{
    char p[ND_PATH_MAX];
    FILE *f;

    if (nd_snprintf(p, sizeof p, "%s/%s", g_ctl, name) != ND_OK)
        return;
    f = fopen(p, "w");
    if (f == NULL)
        return;
    if (value != NULL)
        (void)fputs(value, f);
    (void)fclose(f);
}

static void ctl_body(const char *fixture_name)
{
    ctl_set("body", fixture(fixture_name));
}

/* The call log the stand-in appends to: one "<url>|<range>" per spawn. */
#define MAX_CALLS 32

static struct {
    char url[ND_REMOTE_URL_MAX];
    char range[64];
} g_calls[MAX_CALLS];
static size_t g_n_calls;

static void calls_read(void)
{
    char p[ND_PATH_MAX];
    char line[ND_REMOTE_URL_MAX + 96];
    FILE *f;

    g_n_calls = 0u;
    if (nd_snprintf(p, sizeof p, "%s/calls", g_ctl) != ND_OK)
        return;
    f = fopen(p, "r");
    if (f == NULL)
        return;
    while (g_n_calls < MAX_CALLS && fgets(line, sizeof line, f) != NULL) {
        char *bar = strchr(line, '|');
        char *nl;

        if (bar == NULL)
            continue;
        *bar = '\0';
        nl = strchr(bar + 1, '\n');
        if (nl != NULL)
            *nl = '\0';
        (void)nd_strlcpy(g_calls[g_n_calls].url, line, sizeof g_calls[0].url);
        (void)nd_strlcpy(g_calls[g_n_calls].range, bar + 1, sizeof g_calls[0].range);
        g_n_calls++;
    }
    (void)fclose(f);
}

/* ------------------------------------------------------------------ *
 * The sleep seam, and the progress recorder
 * ------------------------------------------------------------------ */

#define MAX_WAITS 16
static uint32_t g_waits[MAX_WAITS];
static size_t g_n_waits;

static void record_wait(void *ctx, uint32_t seconds)
{
    ND_UNUSED(ctx);
    if (g_n_waits < MAX_WAITS)
        g_waits[g_n_waits] = seconds;
    g_n_waits++;
}

/* Not an array: the number of callbacks is however many read()s the pipe
 * happens to give up, which is not a property worth pinning. What is worth
 * pinning is that it only ever goes forwards and that it arrives at the
 * whole size -- `seen == sorted(seen)` and `seen[-1] == size` in the
 * Python. */
static int64_t g_progress_last;
static int64_t g_progress_total;
static size_t g_n_progress;
static bool g_progress_went_backwards;

static void progress_reset(void)
{
    g_progress_last = 0;
    g_progress_total = -1;
    g_n_progress = 0u;
    g_progress_went_backwards = false;
}

static void record_progress(void *ctx, int64_t done, int64_t total)
{
    ND_UNUSED(ctx);
    if (done < g_progress_last)
        g_progress_went_backwards = true;
    g_progress_last = done;
    g_progress_total = total;
    g_n_progress++;
}

/* ------------------------------------------------------------------ *
 * File helpers
 * ------------------------------------------------------------------ */

static char *real_of(const char *virt)
{
    static char slots[3][ND_PATH_MAX];
    static unsigned next;
    char *p = slots[next % 3u];

    next++;
    if (nd_path_resolve(p, ND_PATH_MAX, virt) != ND_OK)
        return NULL;
    return p;
}

static long size_of(const char *real)
{
    struct stat st;

    return (real != NULL && stat(real, &st) == 0) ? (long)st.st_size : -1;
}

static uint8_t *slurp(const char *real, size_t *len)
{
    FILE *f;
    long n;
    uint8_t *buf;

    *len = 0u;
    if (real == NULL)
        return NULL;
    f = fopen(real, "rb");
    if (f == NULL)
        return NULL;
    (void)fseek(f, 0, SEEK_END);
    n = ftell(f);
    (void)fseek(f, 0, SEEK_SET);
    if (n <= 0) {
        (void)fclose(f);
        return NULL;
    }
    buf = malloc((size_t)n);
    if (buf != NULL && fread(buf, 1u, (size_t)n, f) != (size_t)n) {
        free(buf);
        buf = NULL;
    }
    (void)fclose(f);
    if (buf != NULL)
        *len = (size_t)n;
    return buf;
}

/* Seed "<dest>.part" with the first `n` bytes of the package, or with `n`
 * bytes of something that is NOT the package when `wrong` is true. */
static void seed_partial(const char *dest_virt, long n, bool wrong)
{
    char virt[ND_PATH_MAX];

    if (nd_snprintf(virt, sizeof virt, "%s.part", dest_virt) != ND_OK)
        return;
    if (wrong)
        (void)run("tr '\\0' 'z' < /dev/zero | head -c %ld > '%s'", n, real_of(virt));
    else
        (void)run("head -c %ld '%s' > '%s'", n, fixture("package.bin"), real_of(virt));
}

static void clear_downloads(void)
{
    (void)run("rm -f '%s/dl/'*", g_sandbox);
}

/* The one download this test ever writes, as a virtual path under the
 * sandbox root, and the size of the committed package fixture. */
#define DEST     "/dl/UPDATE.ndsw"
#define DESTPART "/dl/UPDATE.ndsw.part"
#define PKG_SIZE 4000

/* ------------------------------------------------------------------ *
 * 1. Naming
 * ------------------------------------------------------------------ */

static void test_asset_name(void)
{
    char out[ND_REMOTE_ASSET_MAX];
    char tiny[8];

    /* qemu and luckfox are different builds; one release holds both. */
    CHECK_INT(nd_remote_asset_name("luckfox-armv7", out, sizeof out), ND_OK, "asset_name works");
    CHECK_STR(out, "UPDATE-luckfox-armv7.ndsw", "the asset name carries the platform");
    (void)nd_remote_asset_name("qemu-aarch64", out, sizeof out);
    CHECK_STR(out, "UPDATE-qemu-aarch64.ndsw", "and the other platform too");

    (void)nd_remote_asset_name(NULL, out, sizeof out);
    CHECK_STR(out, "UPDATE-.ndsw", "a missing platform is the empty string, matching nothing");

    /* A truncated asset name would match no asset and read as "nothing
     * published", which is a lie about the release rather than the buffer. */
    CHECK_INT(nd_remote_asset_name("luckfox-armv7", tiny, sizeof tiny), ND_ERR_TOOLONG,
              "a name that does not fit is refused, never truncated");
}

static void test_repo_override(void)
{
    CHECK_STR(nd_remote_repo(), ND_REMOTE_DEFAULT_REPO, "the project's own repository by default");

    /* So a fork, or a laptop serving a build over the LAN, does not need a
     * rebuilt image. */
    (void)setenv(ND_REMOTE_REPO_ENV, "someone/else", 1);
    CHECK_STR(nd_remote_repo(), "someone/else", "the repository can be pointed elsewhere");

    /* `os.environ.get(REPO_ENV) or DEFAULT_REPO`: empty is falsy. */
    (void)setenv(ND_REMOTE_REPO_ENV, "", 1);
    CHECK_STR(nd_remote_repo(), ND_REMOTE_DEFAULT_REPO, "an empty override falls back");
    (void)unsetenv(ND_REMOTE_REPO_ENV);
}

/* ------------------------------------------------------------------ *
 * 2. Version ordering, against the real Python
 * ------------------------------------------------------------------ */

static void test_version_order_matches_python(void)
{
    char line[512];
    FILE *f = fopen(fixture("version_order.txt"), "r");
    size_t pairs = 0u;
    size_t disagreed = 0u;

    if (f == NULL) {
        CHECK(false, "version_order.txt is readable");
        return;
    }
    while (fgets(line, sizeof line, f) != NULL) {
        char *first;
        char *second;
        char *nl;
        bool want;
        bool got;

        if (line[0] == '#')
            continue;
        nl = strchr(line, '\n');
        if (nl != NULL)
            *nl = '\0';
        first = strchr(line, '|');
        if (first == NULL)
            continue;
        *first = '\0';
        second = strchr(first + 1, '|');
        if (second == NULL)
            continue;
        *second = '\0';

        want = (second[1] == '1');
        got = nd_remote_is_newer(line, first + 1);
        pairs++;
        if (got != want) {
            disagreed++;
            if (disagreed <= 5u)
                (void)fprintf(stderr,
                              "FAIL %s  is_newer(\"%s\", \"%s\"): C says %d, remote.py says %d\n",
                              __FILE__, line, first + 1, (int)got, (int)want);
        }
    }
    (void)fclose(f);

    CHECK(pairs > 500u, "the whole ordering oracle was read");
    CHECK_INT(disagreed, 0, "the C agrees with remote.py on every ordered pair");
    g_checks += (int)pairs; /* each pair really was an assertion */
}

static void test_version_order_spot_checks(void)
{
    nd_verkey a;
    nd_verkey b;

    /* The one that made the phone sit on 0.3.9a for ever, telling its owner
     * it was up to date. Compared as text, "0.3.9a" > "0.3.10a". */
    CHECK(nd_remote_is_newer("0.3.10a", "0.3.9a"), "0.3.10a is newer than 0.3.9a");
    CHECK(!nd_remote_is_newer("0.3.9a", "0.3.10a"), "and not the other way round");

    nd_verkey_parse("0.4.0a", &a);
    nd_verkey_parse("0.3.99a", &b);
    CHECK(nd_verkey_cmp(&a, &b) > 0, "0.4.0a sorts above 0.3.99a");

    CHECK(!nd_remote_is_newer("0.3.7a", "0.3.7a"), "the same version is not offered");
    CHECK(nd_remote_is_newer("0.3.7a", NULL), "anything is newer than nothing");
    CHECK(nd_remote_is_newer("0.3.7a", ""), "including the empty string");

    /* Python tuple ordering: a prefix is smaller than what it is a prefix
     * of, so 0.3.7 is older than 0.3.7.1. */
    nd_verkey_parse("0.3.7", &a);
    nd_verkey_parse("0.3.7.1", &b);
    CHECK(nd_verkey_cmp(&a, &b) < 0, "a prefix is the smaller key");

    /* A chunk that is not <digits><letters> sorts as (-1, chunk), below
     * every numeric chunk -- which is why a stray "v" makes a version
     * OLDER rather than newer. */
    CHECK(!nd_remote_is_newer("v0.3.7a", "0.3.7a"), "a tag that kept its v does not win");

    nd_verkey_parse("  0.3.7a  ", &a);
    nd_verkey_parse("0.3.7a", &b);
    CHECK_INT(nd_verkey_cmp(&a, &b), 0, "str.strip() -- surrounding space is not a version");
}

/* ------------------------------------------------------------------ *
 * 3. Asking GitHub
 * ------------------------------------------------------------------ */

static void test_latest_picks_this_platform(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("releases.json");

    /* The expectations here are not invented: remote.py was run against this
     * exact fixture and answered version 0.3.11a, size 4000. See
     * neodct/tests/remote/README.md. */
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_OK,
              "a release with this platform's asset is found");
    CHECK_STR(rel.version, "0.3.11a", "the newest VERSION, and its leading v is gone");
    CHECK_STR(rel.tag, "v0.3.11a", "the tag keeps its v -- it is a git ref");
    CHECK_INT(rel.size, 4000, "the size is this platform's asset, not the other one's");
    CHECK(strstr(rel.url, "UPDATE-luckfox-armv7.ndsw") != NULL, "and so is the URL");
    CHECK(rel.prerelease, "a prerelease is still an update -- all of them are");

    scenario_reset();
    ctl_body("releases.json");
    CHECK_INT(nd_remote_latest("qemu-aarch64", &rel, why, sizeof why), ND_UPD_OK,
              "the same listing answers for the other platform");
    CHECK_INT(rel.size, 4001, "with the other platform's asset");
}

static void test_the_endpoint_the_phone_asks_for(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("releases.json");
    (void)nd_remote_latest("luckfox-armv7", &rel, why, sizeof why);
    calls_read();

    CHECK_INT(g_n_calls, 1, "latest() makes exactly one request");
    if (g_n_calls == 0u)
        return;

    /* This is the bug that cost every release its updates: /releases/latest
     * ignores prereleases, every NeoDCT release IS one, so that endpoint
     * answered 404 and the phone reported "no published release" -- for
     * every release ever made. */
    CHECK_STR(g_calls[0].url,
              "https://api.github.com/repos/BubbletopTag/neodct/releases?per_page=30",
              "the phone asks for the release LIST, per_page=30");
    CHECK(strstr(g_calls[0].url, "/releases/latest") == NULL,
          "and never for /releases/latest, which ignores prereleases");
    CHECK_STR(g_calls[0].range, "", "a listing is not a range request");
}

static void test_newest_version_not_newest_publication(void)
{
    nd_release list[8];
    size_t n = 0u;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("releases.json");

    /* GitHub lists by publication date and 0.3.2a is first in the fixture.
     * A reader ordering by that would offer a downgrade as an update. */
    CHECK_INT(
        nd_remote_all_releases("luckfox-armv7", ND_RELEASES_LIMIT, list, 8u, &n, why, sizeof why),
        ND_UPD_OK, "all_releases reads the listing");
    CHECK_INT(n, 3, "three of the four releases carry a luckfox asset");
    if (n == 3u) {
        /* Publication order, exactly as remote.all_releases returned it. */
        CHECK_STR(list[0].version, "0.3.2a", "all_releases keeps GitHub's order");
        CHECK_STR(list[1].version, "0.3.11a", "which is publication order");
        CHECK_STR(list[2].version, "0.3.10a", "and not version order");
    }
}

/* The other fixtures are hand-written to exercise a shape. This one is not:
 * releases-live.json is what api.github.com actually answered for this
 * repository, captured verbatim -- the real ids, the real digests, the
 * nested uploader objects, the release notes with their newlines, and the
 * real asset sizes. It is here because a parser that handles a tidy fixture
 * and chokes on production bytes is the failure nobody sees until a phone
 * is in somebody's hand.
 *
 * Both platforms, because ONE RELEASE CARRIES BOTH and picking the wrong
 * asset is a 56 MB mistake. The sizes differ between them (56,436,037 for
 * the luckfox against 58,828,100 for qemu in 0.3.14a), which is what makes
 * the assertion worth making: getting the platform wrong would still return
 * a plausible-looking release. */
static void test_the_real_listing_parses_for_both_platforms(void)
{
    static const struct {
        const char *platform;
        const char *asset;
        int64_t newest_size;
        int64_t older_size;
    } CASES[] = {
        {"luckfox-armv7", "UPDATE-luckfox-armv7.ndsw", 56436037, 56039086},
        {"qemu-aarch64", "UPDATE-qemu-aarch64.ndsw", 58828100, 64095912},
    };
    size_t c;

    for (c = 0u; c < sizeof CASES / sizeof CASES[0]; c++) {
        nd_release list[8];
        size_t n = 0u;
        char why[ND_REMOTE_WHY_MAX];

        scenario_reset();
        ctl_body("releases-live.json");

        CHECK_INT(nd_remote_all_releases(CASES[c].platform, ND_RELEASES_LIMIT, list, 8u, &n, why,
                                         sizeof why),
                  ND_UPD_OK, "the real listing parses");
        CHECK_INT(n, 2, "both captured releases carry an asset for this platform");
        if (n != 2u)
            continue;

        /* Publication order, newest first, as GitHub returned it. */
        CHECK_STR(list[0].version, "0.3.14a", "0.3.14a is first");
        CHECK_STR(list[1].version, "0.3.13a", "0.3.13a second");

        /* The tag has no leading 'v' here, so version == tag. */
        CHECK_STR(list[0].tag, "0.3.14a", "and the tag is the tag");

        CHECK(strstr(list[0].url, CASES[c].asset) != NULL,
              "the URL is this platform's asset and not the other one");
        CHECK_INT(list[0].size, CASES[c].newest_size, "and GitHub's size for it");
        CHECK_INT(list[1].size, CASES[c].older_size, "and for the older one");

        /* Every NeoDCT release is a prerelease -- which is why latest() is
         * built on this and not on GitHub's /releases/latest, an endpoint
         * that ignores prereleases and answered 404 for this repository. */
        CHECK(list[0].prerelease, "the real releases are prereleases");
        CHECK(list[0].notes[0] != '\0', "and the notes came through");
    }
}

static void test_a_release_without_this_platform_is_skipped(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    /* The newest release in releases.json for a luckfox is 0.3.11a; 0.3.10a
     * is older. The qemu-only 0.3.9a sits between them in the fixture and
     * must simply not be considered -- an entry you cannot pick is worse
     * than one that is not there. */
    scenario_reset();
    ctl_body("releases-qemu-only.json");
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NO_PACKAGE,
              "nothing published for this phone is NoRelease, not an error");
    CHECK(strstr(why, "UPDATE-luckfox-armv7.ndsw") != NULL, "and says which asset was wanted");
    CHECK_STR(rel.version, "", "with nothing handed back");
}

static void test_garbage_and_the_wrong_shape(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("not-json.html");
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "a captive portal's HTML is a network error");
    CHECK_STR(why, "GitHub sent something that is not JSON", "in remote.py's own words");

    /* The single-release endpoint returns an object. Asking for the list and
     * getting one back means something is wrong. */
    scenario_reset();
    ctl_body("one-object.json");
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "a bare object is not a list of releases");
    CHECK_STR(why, "GitHub did not send a list of releases", "again in remote.py's words");
}

static void test_http_statuses(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("not-json.html");
    ctl_set("status", "404");
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NO_PACKAGE,
              "404 is NoRelease -- the repository has nothing published");
    CHECK(strstr(why, "no published release for BubbletopTag/neodct") != NULL,
          "naming the repository it asked about");

    scenario_reset();
    ctl_body("not-json.html");
    ctl_set("status", "503");
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "every other HTTP error is a network error");
    CHECK_STR(why, "GitHub said 503 Service Unavailable", "with the code and the reason phrase");
}

static void test_a_redirect_chain_reports_the_last_status(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    /* GitHub's asset URLs 302 to objects.githubusercontent.com, so every
     * download is a chain and the status that matters is the last one. A
     * parser that took the FIRST status line would read 302 here and never
     * deliver a byte. */
    scenario_reset();
    ctl_body("releases.json");
    ctl_set("redirect", "");
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_OK,
              "a 302 ahead of the real response is followed, not reported");
    CHECK_STR(rel.version, "0.3.11a", "and the body still arrives");
}

static void test_a_proxy_connect_response_is_not_the_answer(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    /* NOT hypothetical. The exact argv nd_remote.c builds was run by hand
     * against api.github.com from a machine behind an HTTP proxy, and curl
     * dumped two header blocks to its -D target:
     *
     *     HTTP/1.1 200 Connection Established     <- the CONNECT tunnel
     *     HTTP/1.1 403 Forbidden                  <- the actual answer
     *
     * The tunnel's 200 is not the answer to anything, and a reader holding
     * only that would write a 403's error page into the .part file
     * believing it had a package. nd_remote.c therefore drains the header
     * descriptor to EAGAIN before it looks at the body, so the answer never
     * depends on how much of the pipe one read happened to return.
     *
     * WHAT THIS TEST DOES AND DOES NOT PIN. It pins the outcome: a proxied
     * 403 is reported as 403, no error page reaches the card, and a tunnel
     * in front of a good response is invisible. It does NOT reproduce the
     * interleaving that makes a one-read-per-wakeup reader lose the second
     * block -- that needs both header blocks and the first body bytes to
     * land between two poll() wakeups, which one process can do and a shell
     * script cannot. The fixture writes its headers in a single copy and
     * pads the tunnel block past 20 kB to get as close as a shell can. The
     * drain-to-EAGAIN is what actually removes the dependence; this test is
     * the regression net around the behaviour it protects. */
    scenario_reset();
    ctl_body("not-json.html");
    ctl_set("connect", "");
    ctl_set("status", "403");
    why[0] = '\0';

    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "the tunnel's 200 does not hide the 403 behind it");
    CHECK_STR(why, "GitHub said 403 Forbidden", "the real status is the one reported");

    /* And the same through the download path, where getting it wrong puts
     * an error page on the card under the package's name. */
    scenario_reset();
    clear_downloads();
    ctl_body("not-json.html");
    ctl_set("connect", "");
    ctl_set("status", "403");

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 1, NULL,
                                 why, sizeof why),
              ND_UPD_ERR_NETWORK, "a proxied 403 fails the download");
    CHECK_INT(size_of(real_of(DESTPART)), 0, "with no error page written to the card");

    /* A tunnel ahead of a good response must still work. */
    scenario_reset();
    ctl_body("releases.json");
    ctl_set("connect", "");
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_OK,
              "and a proxy in front of a working request is invisible");
    CHECK_STR(rel.version, "0.3.11a", "with the listing intact");
}

static void test_an_insecure_asset_url_is_skipped(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    /* DIVERGENCE, asserted so it cannot drift back. Against this fixture
     * remote.py offers 0.3.12a with an http:// asset URL; the C skips that
     * entry and offers 0.3.8a instead. Downloading a rootfs over plaintext
     * is refused rather than left for the signature check to catch, and the
     * direction is "offer an older release", never "offer a worse one". */
    scenario_reset();
    ctl_body("releases-insecure-url.json");
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_OK,
              "the listing is still usable");
    CHECK_STR(rel.version, "0.3.8a", "the http:// entry is skipped, not offered");
}

static void test_a_bad_repository_override_is_refused(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    ctl_body("releases.json");
    (void)setenv(ND_REMOTE_REPO_ENV, "someone else/with a space", 1);
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "a repository name that cannot go in a URL is refused");
    CHECK(strstr(why, ND_REMOTE_REPO_ENV) != NULL, "naming the variable to fix");
    calls_read();
    CHECK_INT(g_n_calls, 0, "and nothing is spawned to find out");

    (void)setenv(ND_REMOTE_REPO_ENV, "someone/else", 1);
    scenario_reset();
    ctl_body("releases.json");
    (void)nd_remote_latest("luckfox-armv7", &rel, why, sizeof why);
    calls_read();
    CHECK(g_n_calls == 1u && strstr(g_calls[0].url, "/repos/someone/else/releases") != NULL,
          "a good override reaches the URL");
    (void)unsetenv(ND_REMOTE_REPO_ENV);
}

static void test_no_curl_at_all(void)
{
    nd_release rel;
    char why[ND_REMOTE_WHY_MAX];

    /* A broken image, and the one failure this code can report without
     * opening anything. It is also what makes the rest of the suite
     * network-proof: with no curl found, nothing can be reached. */
    (void)setenv("PATH", "/nonexistent-so-there-is-no-curl", 1);
    why[0] = '\0';
    CHECK_INT(nd_remote_latest("luckfox-armv7", &rel, why, sizeof why), ND_UPD_ERR_NETWORK,
              "a phone with no curl cannot reach GitHub");
    CHECK_STR(why, "cannot reach GitHub: no curl on this phone", "and says so plainly");
    CHECK(path_with_fake_curl(), "the stand-in goes back on PATH");
}

/* ------------------------------------------------------------------ *
 * 4. Downloading
 * ------------------------------------------------------------------ */

/* The reassembled file must equal the fixture byte for byte. A length check
 * alone would pass a package whose first 200 bytes were written twice. */
static void check_matches_package(const char *what)
{
    size_t got_len = 0u;
    size_t want_len = 0u;
    uint8_t *got = slurp(real_of(DEST), &got_len);
    uint8_t *want = slurp(fixture("package.bin"), &want_len);

    CHECK(got != NULL && want != NULL && got_len == want_len && memcmp(got, want, want_len) == 0,
          what);
    free(got);
    free(want);
}

static void test_a_complete_download(void)
{
    char why[ND_REMOTE_WHY_MAX];
    int64_t written = 0;

    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    progress_reset();

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, record_progress,
                                 NULL, 1, &written, why, sizeof why),
              ND_UPD_OK, "a complete download succeeds");
    CHECK_INT(written, PKG_SIZE, "and reports what it wrote");
    check_matches_package("the file on the card is the package, byte for byte");
    CHECK_INT(size_of(real_of(DESTPART)), -1,
              "the .part is gone -- it is renamed only when complete");

    CHECK(g_n_progress > 0u, "progress was reported as it went");
    CHECK(!g_progress_went_backwards, "and only ever went forwards");
    CHECK_INT(g_progress_last, PKG_SIZE, "ending at the whole size");
    CHECK_INT(g_progress_total, PKG_SIZE, "with the total the caller asked for");
}

static void test_a_truncated_download_never_looks_installable(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* A dropped carrier mid-download is the expected case on this phone.
     * What must never happen is a short file sitting under the real name,
     * where the update flow would find it and try to install it. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("cut", "40");
    ctl_set("exit", "0"); /* short, but not an error: the Python's fixture */

    why[0] = '\0';
    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, 100, NULL, NULL, 1, NULL, why,
                                 sizeof why),
              ND_UPD_ERR_NETWORK, "a short download is refused");
    CHECK(strstr(why, "stopped early") != NULL, "with remote.py's own wording");
    CHECK_INT(size_of(real_of(DEST)), -1, "nothing lands under the installable name");
    /* The bytes on the card are good as far as they go, and this phone
     * fetches 53 MB over a carrier. Deleting them meant every attempt began
     * at zero. */
    CHECK_INT(size_of(real_of(DESTPART)), 40, "and what did arrive is kept");
}

static void test_resuming_asks_only_for_the_rest(void)
{
    char why[ND_REMOTE_WHY_MAX];

    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    seed_partial(DEST, 200, false);

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 1, NULL,
                                 why, sizeof why),
              ND_UPD_OK, "a seeded partial finishes");
    calls_read();
    CHECK_INT(g_n_calls, 1, "in one request");
    if (g_n_calls > 0u)
        CHECK_STR(g_calls[0].range, "bytes=200-",
                  "asking for the rest, not for the whole file again");
    check_matches_package("and the reassembled package is right");
}

static void test_a_download_picks_up_where_it_stopped(void)
{
    char why[ND_REMOTE_WHY_MAX];
    int64_t written = 0;

    /* A carrier that drops after every 1000 bytes -- curl exit 18 each
     * time, including on the attempt that happens to finish the file. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("cut", "1000");
    g_n_waits = 0u;

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 10,
                                 &written, why, sizeof why),
              ND_UPD_OK, "four dropped connections still deliver the package");
    CHECK_INT(written, PKG_SIZE, "all of it");
    check_matches_package("reassembled byte for byte across the drops");

    calls_read();
    CHECK_INT(g_n_calls, 4, "one attempt per 1000-byte piece");
    if (g_n_calls == 4u) {
        CHECK_STR(g_calls[0].range, "", "the first attempt asks for no range");
        CHECK_STR(g_calls[1].range, "bytes=1000-", "then from 1000");
        CHECK_STR(g_calls[2].range, "bytes=2000-", "then from 2000");
        CHECK_STR(g_calls[3].range, "bytes=3000-", "then from 3000");
    }
}

static void test_a_server_that_ignores_range_is_started_over(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* THE TRAP. Answering 200 to a Range request means the whole file is
     * coming. Appending it would write the first 150 bytes twice and
     * produce a 4150-byte package that fails its sha256 with nothing to
     * explain why -- so the partial is truncated and the download starts
     * over. The seeded bytes are deliberately NOT the package's, so an
     * append would be visible in the content as well as the length. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("ignore_range", "");
    seed_partial(DEST, 150, true);

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 3, NULL,
                                 why, sizeof why),
              ND_UPD_OK, "a server that ignores Range still delivers");
    calls_read();
    CHECK(g_n_calls >= 1u && strcmp(g_calls[0].range, "bytes=150-") == 0,
          "the Range was asked for");
    CHECK_INT(size_of(real_of(DEST)), PKG_SIZE, "the partial was NOT appended to");
    check_matches_package("and the bytes are the package, not the package after junk");
}

static void test_a_partial_longer_than_the_package_is_thrown_away(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* Left over from a different, larger package. Resuming from past the
     * end would ask for a range no server can serve. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    seed_partial(DEST, 5000, true);

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 3, NULL,
                                 why, sizeof why),
              ND_UPD_OK, "an over-long partial does not stop the download");
    calls_read();
    CHECK(g_n_calls >= 1u && g_calls[0].range[0] == '\0',
          "it started clean, with no Range asked for");
    check_matches_package("and the package is right");
}

static void test_giving_up_still_leaves_the_progress(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* Out of attempts is not the same as out of luck: the next time the
     * owner presses the button it carries on from here. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("cut", "100");
    g_n_waits = 0u;

    CHECK(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 3, NULL,
                             why, sizeof why) != ND_UPD_OK,
          "three cut attempts do not finish a 4000-byte package");
    CHECK_INT(size_of(real_of(DEST)), -1, "nothing installable is left behind");
    CHECK_INT(size_of(real_of(DESTPART)), 300, "but all three attempts' bytes are kept");
}

static void test_the_backoff(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* When the bearer drops the whole data session goes, DNS included, and
     * five immediate retries are five failures in under a second -- after
     * which the phone has given up on a connection that would have come
     * back on its own. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("fail_first", "99");
    g_n_waits = 0u;

    CHECK(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 4, NULL,
                             why, sizeof why) != ND_UPD_OK,
          "four failures give up");
    CHECK_INT(g_n_waits, 3, "with three waits between four attempts");
    if (g_n_waits == 3u) {
        CHECK_INT(g_waits[0], 5, "5 seconds");
        CHECK_INT(g_waits[1], 10, "then 10");
        CHECK_INT(g_waits[2], 20, "then 20 -- doubling");
    }
    CHECK(strstr(why, "Could not resolve host") != NULL,
          "and curl's own reason reaches the screen");

    /* Doubling for ever means a phone that looks hung rather than patient. */
    scenario_reset();
    ctl_body("package.bin");
    ctl_set("fail_first", "99");
    g_n_waits = 0u;
    (void)nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 8, NULL,
                             why, sizeof why);
    CHECK_INT(g_n_waits, 7, "seven waits between eight attempts");
    if (g_n_waits == 7u) {
        CHECK_INT(g_waits[4], ND_REMOTE_RETRY_BACKOFF_MAX, "the fifth wait is already capped");
        CHECK_INT(g_waits[6], ND_REMOTE_RETRY_BACKOFF_MAX, "and it stays capped");
    }
}

static void test_the_first_attempt_does_not_wait(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* Nothing has failed yet. Making the owner wait five seconds before the
     * first byte would be punishing them for the carrier. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    g_n_waits = 0u;

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 5, NULL,
                                 why, sizeof why),
              ND_UPD_OK, "a download that works, works");
    CHECK_INT(g_n_waits, 0, "and nothing waited for it");
}

static void test_a_dns_failure_is_retried_not_fatal(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* The owner's report: "It'll say it timed out then lose internet
     * completely. Temporary failure in name resolution. But it's still able
     * to make calls." The bearer comes back; the phone should still be
     * trying when it does. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    ctl_set("fail_first", "2");
    g_n_waits = 0u;

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 5, NULL,
                                 why, sizeof why),
              ND_UPD_OK, "two DNS failures are not fatal");
    calls_read();
    CHECK_INT(g_n_calls, 3, "the third attempt got through");
    check_matches_package("and the package is whole");
}

static void test_no_room_on_the_card(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* Better to say so than to fill the card and fail at the last byte. */
    scenario_reset();
    clear_downloads();
    ctl_body("package.bin");
    why[0] = '\0';

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, (int64_t)1 << 60, NULL, NULL,
                                 5, NULL, why, sizeof why),
              ND_UPD_ERR_NO_SPACE, "a package bigger than the card is refused");
    CHECK(strstr(why, "not enough room on the card") != NULL, "in remote.py's own words");
    calls_read();
    CHECK_INT(g_n_calls, 0, "before it starts -- nothing was even spawned");

    /* "cannot tell; let the write fail honestly" -- a directory that cannot
     * be measured must not become a refusal nobody can act on. */
    CHECK(nd_remote_enough_space("/definitely/not/a/directory", 1000),
          "an unmeasurable directory is treated as having room");
    CHECK(nd_remote_enough_space("/dl", 0), "an empty request always fits");
}

static void test_a_404_on_the_asset_is_not_retried(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* remote.NoRelease is not caught by the Python's retry loop either:
     * there is nothing at that URL and waiting will not put anything
     * there. */
    scenario_reset();
    clear_downloads();
    ctl_body("not-json.html");
    ctl_set("status", "404");
    g_n_waits = 0u;

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 5, NULL,
                                 why, sizeof why),
              ND_UPD_ERR_NO_PACKAGE, "a 404 on the asset is NoRelease");
    calls_read();
    CHECK_INT(g_n_calls, 1, "asked once");
    CHECK_INT(g_n_waits, 0, "and not waited on");
    CHECK_INT(size_of(real_of(DEST)), -1, "with nothing written");
}

static void test_the_error_page_is_not_the_package(void)
{
    char why[ND_REMOTE_WHY_MAX];

    /* A 503's body is HTML. It must not reach the .part file: a body byte
     * is only handed to the card after the status that describes it has
     * been read and accepted. */
    scenario_reset();
    clear_downloads();
    ctl_body("not-json.html");
    ctl_set("status", "503");

    CHECK_INT(nd_remote_download("https://example.invalid/pkg", DEST, PKG_SIZE, NULL, NULL, 1, NULL,
                                 why, sizeof why),
              ND_UPD_ERR_NETWORK, "a 503 is a network error");
    CHECK_INT(size_of(real_of(DESTPART)), 0, "and its error page is not appended to the download");
}

/* ------------------------------------------------------------------ *
 * main
 * ------------------------------------------------------------------ */

int main(void)
{
    if (!find_fixtures()) {
        (void)fprintf(stderr, "test_remote: cannot locate neodct/tests/remote\n");
        return 1;
    }
    if (!sandbox_up()) {
        (void)fprintf(stderr, "test_remote: cannot make a sandbox\n");
        return 1;
    }
    if (!fake_curl_install()) {
        (void)fprintf(stderr, "test_remote: cannot install the stand-in curl\n");
        return 1;
    }
    /* Backoff is real on the phone and pointless in a test suite -- the
     * autouse no_waiting fixture, in C. */
    nd_remote_set_sleep_fn(record_wait, NULL);

    test_asset_name();
    test_repo_override();
    test_version_order_matches_python();
    test_version_order_spot_checks();

    test_latest_picks_this_platform();
    test_the_endpoint_the_phone_asks_for();
    test_newest_version_not_newest_publication();
    test_the_real_listing_parses_for_both_platforms();
    test_a_release_without_this_platform_is_skipped();
    test_garbage_and_the_wrong_shape();
    test_http_statuses();
    test_a_redirect_chain_reports_the_last_status();
    test_a_proxy_connect_response_is_not_the_answer();
    test_an_insecure_asset_url_is_skipped();
    test_a_bad_repository_override_is_refused();
    test_no_curl_at_all();

    test_a_complete_download();
    test_a_truncated_download_never_looks_installable();
    test_resuming_asks_only_for_the_rest();
    test_a_download_picks_up_where_it_stopped();
    test_a_server_that_ignores_range_is_started_over();
    test_a_partial_longer_than_the_package_is_thrown_away();
    test_giving_up_still_leaves_the_progress();
    test_the_backoff();
    test_the_first_attempt_does_not_wait();
    test_a_dns_failure_is_retried_not_fatal();
    test_no_room_on_the_card();
    test_a_404_on_the_asset_is_not_retried();
    test_the_error_page_is_not_the_package();

    nd_remote_set_sleep_fn(NULL, NULL);
    (void)setenv("PATH", g_path_keep, 1);
    if (g_sandbox[0] != '\0')
        (void)run("rm -rf '%s'", g_sandbox);

    (void)printf("test_remote: %d checks, %d failures\n", g_checks, g_fail);
    return g_fail == 0 ? 0 : 1;
}
