/* test_platform.c -- the three-valued answer, and the one that must not
 * collapse into either of the others.
 *
 * nd_platform.h's rule is the whole subject of this file: a missing or
 * unreadable /NeoDCT/platform is ND_PLATFORM_UNKNOWN, and UNKNOWN is a real
 * answer rather than a default that quietly means "hw" on a build host or
 * "qemu" on a phone that lost its flag. Both of those defaults would be
 * silent -- the first arms hardware waits in every unit test, the second is
 * the 0.5.9a regression class in reverse -- so the case that most needs a
 * test is the one where the file is not there at all.
 *
 * The fixture is the case root. nd_platform.c reads through
 * nd_props_parse_settings(), which resolves through ND_ROOT, so writing
 * "/NeoDCT/platform" under the scratch directory is enough to be a phone for
 * one case with no test-only branch anywhere in the module.
 *
 * Every case goes through one of the given_* helpers below, and each of them
 * drops the cache. That is not tidiness: nd_platform() resolves once per
 * process on purpose -- a running phone must not see its own platform change
 * under it -- so without the reset every case after the first would be
 * asserting on the first case's fixture.
 */

#include <stdlib.h>
#include <string.h>

#include "nd_crash.h"
#include "nd_paths.h"
#include "nd_platform.h"

#include "platform_test.h"

/* The record as post-build-system-metadata.sh writes it, comment line and
 * all. Spelled out here rather than generated, so that a change to the
 * script's format has to be made in two places and noticed in one of them. */
#define HW_RECORD                                                    \
    "# Generated by post-build-system-metadata.sh -- do not edit.\n" \
    "platform=hw\n"                                                  \
    "board=luckfox-pico-mini-b\n"                                    \
    "image=luckfox-armv7\n"

#define QEMU_RECORD                                                  \
    "# Generated by post-build-system-metadata.sh -- do not edit.\n" \
    "platform=qemu\n"                                                \
    "board=qemu-virt\n"                                              \
    "image=qemu-aarch64\n"

/* No file at all: a developer's checkout, a host test, or an image built
 * before the flag existed. It really removes the record rather than trusting
 * the case root to be empty, because two of the cases below walk from a
 * written record to no record inside one case. */
static void given_no_platform_record(void)
{
    char resolved[ND_PATH_MAX];

    (void)unsetenv(ND_ENV_PLATFORM);
    if (nd_path_resolve(resolved, sizeof resolved, ND_PATH_PLATFORM) == ND_OK)
        (void)remove(resolved);
    CHECK(!nd_path_exists(ND_PATH_PLATFORM));
    nd_platform__reset_cache();
}

static void given_a_platform_record(const char *text)
{
    (void)unsetenv(ND_ENV_PLATFORM);
    pt_write_text(ND_PATH_PLATFORM, text);
    nd_platform__reset_cache();
}

/* The override, which the header says carries a platform word and never a
 * board. `record` may be NULL for "and no file either". */
static void given_the_environment_says(const char *word, const char *record)
{
    if (record != NULL)
        pt_write_text(ND_PATH_PLATFORM, record);
    if (word != NULL)
        (void)setenv(ND_ENV_PLATFORM, word, 1);
    else
        (void)unsetenv(ND_ENV_PLATFORM);
    nd_platform__reset_cache();
}

/* ------------------------------------------------------------------ *
 * The two answers an image is allowed to give
 * ------------------------------------------------------------------ */

static void test_hw_is_hardware_and_nothing_else(void)
{
    given_a_platform_record(HW_RECORD);

    CHECK_INT(nd_platform(), ND_PLATFORM_HW);
    CHECK_STR(nd_platform_name(), "hw");
    CHECK(nd_platform_is_hw());
    CHECK(!nd_platform_is_qemu());
    CHECK_STR(nd_platform_board(), "luckfox-pico-mini-b");
}

static void test_qemu_is_the_emulator_and_nothing_else(void)
{
    given_a_platform_record(QEMU_RECORD);

    CHECK_INT(nd_platform(), ND_PLATFORM_QEMU);
    CHECK_STR(nd_platform_name(), "qemu");
    CHECK(nd_platform_is_qemu());
    CHECK(!nd_platform_is_hw());
    CHECK_STR(nd_platform_board(), "qemu-virt");
}

/* ------------------------------------------------------------------ *
 * And the third one, which is the reason the module exists
 * ------------------------------------------------------------------ */

/* THE CENTRAL CASE. No file: not hardware, not the emulator, and both
 * predicates false at once. A build host is in this state, so is every other
 * test binary in this directory, and so is a phone whose image was built
 * before post-build-system-metadata.sh learned to write the record. */
static void test_a_missing_record_is_unknown_and_not_either_default(void)
{
    given_no_platform_record();

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
    CHECK_STR(nd_platform_name(), "unknown");
    /* Both false. If a later refactor makes one of these the negation of the
     * other, this is the check that stops it: !is_qemu() would be true here
     * and would mean "hardware" to the first person who read it. */
    CHECK(!nd_platform_is_hw());
    CHECK(!nd_platform_is_qemu());
}

static void test_a_word_this_build_has_never_heard_of_is_unknown(void)
{
    /* "luckfox" is the tempting one: it is a real string from
     * system.os.platform, it names the right machine, and it is still not a
     * token this module has been taught. Guessing at it would be how the file
     * format and the reader start disagreeing. */
    given_a_platform_record("platform=luckfox\nboard=luckfox-pico-mini-b\n");

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
    CHECK(!nd_platform_is_hw());
    CHECK(!nd_platform_is_qemu());
}

static void test_a_record_with_no_platform_key_is_unknown(void)
{
    given_a_platform_record("board=luckfox-pico-mini-b\nimage=luckfox-armv7\n");

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
    CHECK_STR(nd_platform_name(), "unknown");
}

/* nd_props.h B-1: a file that is not valid UTF-8 yields an EMPTY map rather
 * than whatever parsed before the bad byte. Empty map, no platform key,
 * UNKNOWN -- which is the answer that costs nothing to be wrong about. */
static void test_a_file_that_is_not_a_prop_file_is_unknown(void)
{
    (void)unsetenv(ND_ENV_PLATFORM);
    pt_write(ND_PATH_PLATFORM, "\x00\xff platform=hw\n", 15u);
    nd_platform__reset_cache();

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
}

/* ------------------------------------------------------------------ *
 * The board
 * ------------------------------------------------------------------ */

static void test_the_board_is_empty_and_never_null_without_one(void)
{
    given_a_platform_record("platform=hw\n");

    CHECK(nd_platform_board() != NULL);
    CHECK_STR(nd_platform_board(), "");
    /* The platform word still parsed, so the machine is still hardware. A
     * board is extra detail, not part of the answer. */
    CHECK(nd_platform_is_hw());
}

static void test_the_board_is_null_safe_under_unknown_too(void)
{
    given_no_platform_record();

    CHECK(nd_platform_board() != NULL);
    CHECK_STR(nd_platform_board(), "");
}

/* Half a record we could not understand is not a fact to quote the other half
 * out of. A caller acting on board= while the platform was UNKNOWN would be
 * making exactly the claim UNKNOWN exists to withhold. */
static void test_a_board_is_not_reported_when_the_platform_word_did_not_parse(void)
{
    given_a_platform_record("platform=potato\nboard=luckfox-pico-mini-b\n");

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
    CHECK_STR(nd_platform_board(), "");
}

/* ------------------------------------------------------------------ *
 * The environment override
 * ------------------------------------------------------------------ */

static void test_the_environment_beats_the_file(void)
{
    given_the_environment_says("hw", QEMU_RECORD);

    CHECK_INT(nd_platform(), ND_PLATFORM_HW);
    CHECK(nd_platform_is_hw());
    /* And it carries NO board, even though the file sitting underneath it
     * names one: a board is a claim about a piece of hardware and an
     * environment variable is not evidence of one. */
    CHECK_STR(nd_platform_board(), "");
}

static void test_the_environment_can_also_say_qemu_over_hardware(void)
{
    given_the_environment_says("qemu", HW_RECORD);

    CHECK(nd_platform_is_qemu());
    CHECK(!nd_platform_is_hw());
}

/* An override this build does not understand is UNKNOWN and does NOT fall
 * through to the file. Falling through would make a typo silently do
 * something -- and the something would be "believe the image", which is the
 * opposite of what someone setting the variable asked for. */
static void test_an_unknown_override_is_unknown_and_does_not_fall_through(void)
{
    given_the_environment_says("hardware", HW_RECORD);

    CHECK_INT(nd_platform(), ND_PLATFORM_UNKNOWN);
    CHECK(!nd_platform_is_hw());
}

/* An empty value is not somebody saying something. The file wins. */
static void test_an_empty_override_is_ignored(void)
{
    given_the_environment_says("", HW_RECORD);

    CHECK_INT(nd_platform(), ND_PLATFORM_HW);
    CHECK_STR(nd_platform_board(), "luckfox-pico-mini-b");
}

/* ------------------------------------------------------------------ *
 * The cache
 * ------------------------------------------------------------------ */

/* Resolved once per process, so a running phone cannot see the answer change
 * under it. The reset exists for tests and for nothing else -- which is worth
 * a check of its own, because a cache that never actually caches would pass
 * every other case in this file. */
static void test_the_answer_is_resolved_once_and_the_reset_is_what_re_reads(void)
{
    given_a_platform_record(QEMU_RECORD);
    CHECK(nd_platform_is_qemu());

    pt_write_text(ND_PATH_PLATFORM, HW_RECORD);
    CHECK(nd_platform_is_qemu()); /* still the cached answer */

    nd_platform__reset_cache();
    CHECK(nd_platform_is_hw());
    CHECK_STR(nd_platform_board(), "luckfox-pico-mini-b");
}

/* ------------------------------------------------------------------ *
 * The one published alias
 * ------------------------------------------------------------------ */

/* nd_crash.h keeps nd_crash_is_simulation() as the published name for this
 * fact and has no caller left in the tree, so this is the only thing standing
 * between it and silent rot. All three states, and the third is the one that
 * matters: it is FALSE under UNKNOWN, so negating it does not mean
 * "hardware". */
static void test_the_crash_handlers_published_alias_still_agrees(void)
{
    given_a_platform_record(QEMU_RECORD);
    CHECK(nd_crash_is_simulation());

    given_a_platform_record(HW_RECORD);
    CHECK(!nd_crash_is_simulation());

    given_no_platform_record();
    CHECK(!nd_crash_is_simulation());
    /* Spelled out, because this is the trap the header warns about: the
     * negation is true here and hardware is not. */
    CHECK(!nd_platform_is_hw());
}

int main(void)
{
    RUN(test_hw_is_hardware_and_nothing_else);
    RUN(test_qemu_is_the_emulator_and_nothing_else);
    RUN(test_a_missing_record_is_unknown_and_not_either_default);
    RUN(test_a_word_this_build_has_never_heard_of_is_unknown);
    RUN(test_a_record_with_no_platform_key_is_unknown);
    RUN(test_a_file_that_is_not_a_prop_file_is_unknown);
    RUN(test_the_board_is_empty_and_never_null_without_one);
    RUN(test_the_board_is_null_safe_under_unknown_too);
    RUN(test_a_board_is_not_reported_when_the_platform_word_did_not_parse);
    RUN(test_the_environment_beats_the_file);
    RUN(test_the_environment_can_also_say_qemu_over_hardware);
    RUN(test_an_unknown_override_is_unknown_and_does_not_fall_through);
    RUN(test_an_empty_override_is_ignored);
    RUN(test_the_answer_is_resolved_once_and_the_reset_is_what_re_reads);
    RUN(test_the_crash_handlers_published_alias_still_agrees);

    /* Left set by the last case would leak into nothing -- this is the end of
     * the process -- but the cache reset is the habit the module asks for and
     * the environment is part of what it caches. */
    (void)unsetenv(ND_ENV_PLATFORM);
    nd_platform__reset_cache();
    return pt_report("test_platform");
}
