/* nd_platform.h -- which machine is this, asked once and answered from the
 * image rather than guessed from the hardware.
 *
 * The answer is baked in at BUILD time, and on an image build that is now
 * literally true: neodct/scripts/platform-id.sh maps the defconfig's image tag
 * to an nd_platform_t enumerator, buildroot/package/neodct/neodct.mk compiles
 * it into libneodct, and it is INSIDE the binary asking the question.
 *
 * The second source is /NeoDCT/platform, which the same helper feeds through
 * post-build-system-metadata.sh, so the file cannot disagree with the image it
 * is part of, and nothing at runtime can edit it: it is inside the squashfs,
 * under dm-verity.
 *
 *     # Generated by post-build-system-metadata.sh -- do not edit.
 *     platform=hw
 *     board=luckfox-pico-mini-b
 *     image=luckfox-armv7
 *
 * ============ WHY THIS EXISTS AT ALL ============
 *
 * Half a dozen places in the tree used to work out where they were running by
 * looking for a device and drawing a conclusion: nd_crash.c and
 * nd_keypadsetup.c tested access("/dev/ttyFIQ0"), S10udevd and S90display
 * tested [ -e /dev/spidev0.0 ], KeypadMapperI2C told the owner "this cannot
 * run in QEMU" on the strength of an empty /dev/i2c-* glob. Every one of those
 * is a proxy, and a proxy is wrong in both directions: a hardware kernel built
 * without the FIQ debugger reads as QEMU, and any emulator that grew a
 * spidev node would read as a phone. The visible damage was real -- a phone
 * whose crash reports were all filed as "QEMU/simulation", and a phone that
 * skipped waiting for its own keypad bus and came up with no keys.
 *
 * ============ WHY THE CONSTANT IS NOT A MACRO YOU CAN SEE ============
 *
 * ND_BUILD_PLATFORM is deliberately NOT declared in this header. It reaches
 * exactly one translation unit -- lib/nd_platform.c -- through a generated
 * header on that object's include path alone, and the reasons are not
 * tidiness:
 *
 *   A .nap must not carry a platform. After DECISIONS.md D1 there is one ABI
 *   and one app.so, and a .nap really does move between the two images; an app
 *   compiled with the constant in it would carry a platform INSIDE the app and
 *   lie about the phone it was installed on.
 *
 *   And a constant visible in two hundred translation units invites
 *   `#if ND_BUILD_PLATFORM == ND_PLATFORM_HW`. #ifdef'ing the two images apart
 *   is how the QEMU build stops being a test of the phone, which is the entire
 *   point of building both from one source. The FACT is published here as an
 *   API; the MACRO is published to nobody.
 *
 * A `#ifndef ND_BUILD_PLATFORM / #define ... UNKNOWN` fallback here would be
 * worse than no name at all: the generated header is on one object's include
 * path, so every other translation unit would compile the fallback and see
 * UNKNOWN as if it were a fact.
 *
 * ============ WHY THE BUILD OUTRANKS THE FILE AND THE ENVIRONMENT ============
 *
 * A build that was told what it is cannot be told otherwise. Both runner-up
 * sources are weaker in a way that matters:
 *
 *   /NeoDCT/platform is verity-covered, but it is a SEPARATE artefact written
 *   by a separate build step, so it can be MISMATCHED. The constant cannot:
 *   it is in the binary doing the asking.
 *
 *   NEODCT_PLATFORM is not part of the image at all. It can come from
 *   /NeoDCT/User/env.sh -- arbitrary shell run as root from the only writable
 *   partition, which survives updates because an update replaces only the
 *   rootfs (AGENTS.md, SECURITY-AUDIT.md section 4 Q5 vector 2). After D1 this
 *   flag is the only thing separating a phone from an emulator, and a
 *   discriminator any environment variable can flip is not one: NEODCT_PLATFORM=qemu
 *   in that file would be a persistent, update-proof way to make a phone file
 *   its crashes as "QEMU/simulation" and simulate its radio.
 *
 * So on an image the constant decides, and the environment is read only so
 * that nd_platform_origin() can say it was ignored. On a build that carries no
 * constant -- the host build, and only that -- nothing changes at all: the
 * environment still wins, then the file, then UNKNOWN.
 *
 * ============ WHY A DISAGREEMENT IS UNKNOWN AND NOT A CASTING VOTE ============
 *
 * When the constant and the record name DIFFERENT machines, nd_platform() is
 * ND_PLATFORM_UNKNOWN for the life of the process, nd_platform_mismatch() is
 * true, and one line goes to the log naming both sides.
 *
 * The two artefacts are two steps of ONE build. If they disagree, what failed
 * is the assembly of the image, and nothing at runtime can know which step was
 * right; preferring the constant is preferring the one we happen to trust
 * today. nd_crash.c's FIQ-node heuristic is the record of what that costs --
 * it was confidently wrong and every crash report it filed said
 * "QEMU/simulation" at the top of the page -- and a wrong confident answer is
 * worse than silence BECAUSE IT IS BELIEVED. Picking a winner quietly would
 * also leave the check with no consequence beyond a log line nobody greps, and
 * a check with no consequence gets deleted within a year.
 *
 * It does not abort, and that is the same trade. nd_platform() is resolved
 * lazily in every process on the phone, from signal-adjacent paths including
 * the crash handler; a phone that bricks itself because two build artefacts
 * disagree is worse than one that runs, claims neither machine, and says so on
 * every screen that reports the machine.
 *
 * Only a record that NAMES A MACHINE can contradict the constant. An absent,
 * unreadable or unintelligible record withholds a claim rather than making a
 * competing one -- the same rule the board= read already follows.
 *
 * ============ WHY THREE VALUES AND NOT TWO ============
 *
 * A missing or unreadable file is ND_PLATFORM_UNKNOWN, which is a genuine
 * answer and not a shorthand for either of the others. Both defaults were
 * considered and both are worse:
 *
 *   defaulting to HW arms every hardware wait on a developer's laptop and in
 *   every unit test -- the first-boot keypad wizard would sit waiting for
 *   /dev/i2c-3 on a machine that has never had one;
 *
 *   defaulting to QEMU is the 0.5.9a regression class in reverse. A real
 *   phone that lost its flag would quietly take every cheap emulator path,
 *   and nd_modem.h records what that looks like from the outside: a phone
 *   telling its owner everything is fine while its radio is unreachable.
 *
 * ============ AND WHY THE HOST BUILD IS TOLD NOTHING, NOT TOLD IT IS A HOST ==
 *
 * A build that carries no constant is UNKNOWN, and there is no fourth value
 * for it, because "the build was told nothing" is not a state separate from
 * the one already named. The build system cannot emit an unrecognised tag at
 * all: platform-id.sh refuses one, the guard in NEODCT_BUILD_CMDS refuses one,
 * and post-build-system-metadata.sh already refuses to write platform=unknown
 * on principle. So ND_BUILD_PLATFORM has exactly three reachable states -- HW,
 * QEMU and absent -- and absent and unknown are the same state twice.
 *
 * A fourth enumerator would also cost what this file already charges for
 * widening the platform word. The three switches over nd_platform_t
 * (nd_platform.c's own word_for(), nd_crash.c's crash_mode_text(),
 * KeypadMapperI2C's nd_kmi2c_i2c_required_text()) all have a `default:`, so a
 * new value would land there SILENTLY with no compiler warning -- and
 * word_for() is the worst of the three, because its default arm spells the new
 * machine "unknown" in every origin line, every crash mode: field and every
 * mismatch log line. And "host" is itself a claim
 * about a machine -- "this is a developer's x86 box" -- of exactly the kind
 * UNKNOWN exists to withhold, and call sites would branch on it within a month.
 * What the mismatch case genuinely needs is a way to fail closed, and that is
 * nd_platform_mismatch(), not a wider vocabulary.
 *
 * ============ THE RULE AT THE CALL SITE ============
 *
 * UNKNOWN may decide a COST question and may never decide a TRUTH question.
 *
 *   "Should I spend ten seconds waiting for a bus that may be coming?"  is a
 *   cost question. UNKNOWN takes the cheap branch: do not wait. Nothing is
 *   claimed; at worst a developer waits zero seconds instead of ten.
 *
 *   "Is there a radio on this board?", "is this crash report from a phone?",
 *   "should a missing i2c bus be a FAILURE rather than a skip?" are truth
 *   questions. UNKNOWN answers none of them, and a call site that needs one
 *   answered has to keep whatever evidence it already had.
 *
 * That is why the two predicates below are separate and why there is no
 * negation helper: !nd_platform_is_qemu() reads as "hardware" and is not,
 * and the day somebody writes it the phone starts making claims about
 * hardware it has never been told it has.
 *
 * A MISMATCH IS INSIDE THAT RULE, not beside it. It is routed into UNKNOWN
 * rather than around it precisely so that every existing call site inherits
 * the rule it already obeys: every truth question goes unanswered and keeps
 * the evidence it had, every cost question takes the cheap branch, and nothing
 * claims a machine whose identity is contested.
 *
 * ============ WHAT THIS IS NOT ============
 *
 * It is not system.os.platform. That value ("qemu-aarch64",
 * "luckfox-armv7") is the update system's compatibility key -- see
 * nd_manifest_check_compatible() and nd_remote_asset_name() -- and its format
 * is load-bearing for every .ndsw ever built. This is a sibling of it, carried
 * in the same generated block, in a file cheap enough to read from a boot
 * script; the image= key holds that same tag for anything that wants it.
 *
 * And it is not a device probe. The modem's SIM-vs-UNREACHABLE gate
 * (nd_modem.h) and the battery's SIM-vs-UNREADABLE gate (nd_battery.h) turn
 * on whether a candidate device actually enumerated, which is a different
 * question with a different failure mode; both headers record at length what
 * conflating the two cost. Do not route either of them through here.
 *
 * Two more that read like guesses and are not, listed because both have
 * already been looked at once and the reasoning should not have to be
 * rediscovered. nd_log_redirect_serial() picks /dev/ttyFIQ0 over /dev/ttyAMA0
 * by testing the node it is about to open, which is evidence about that node
 * rather than a proxy for the machine -- asking here would hand a hardware
 * kernel with no FIQ debugger a console that does not exist. And
 * nd_nap_phone_arch() (nd_nap.h) reads uname(2) because a .nap carries native
 * code: that is an ABI question about the CPU running now, it has a
 * host-x86_64 answer this file will never have, and an UNKNOWN there would
 * turn a missing flag into a phone that can install nothing. Both headers
 * carry the long version at the call site.
 */

#ifndef ND_PLATFORM_H_INCLUDED
#define ND_PLATFORM_H_INCLUDED

#include "nd_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* The environment override, checked before the file ON A BUILD THAT CARRIES NO
 * CONSTANT. One caller in practice now: a host test that wants to be a phone
 * for one case. It carries the platform word only ("qemu" or "hw") -- a board
 * name has to come from a real record, because a board is a claim about a
 * piece of hardware and an environment variable is not evidence of one.
 * Anything else, including an empty value, is ignored.
 *
 * THE SECOND CALLER HAD TO GO. It used to be "a developer bisecting something
 * under QEMU", and on an image this variable no longer wins -- see WHY THE
 * BUILD OUTRANKS THE FILE AND THE ENVIRONMENT above. Asking the flag to
 * pretend an emulator is a phone is asking it to lie about the one thing it
 * exists to tell the truth about, and the file it would arrive in is
 * update-proof. A developer bisects with nd-shoot and the unit tests, on the
 * host build, where the override still works exactly as it always did.
 *
 * What replaces the lost capability for tests is nd_platform__set_build(),
 * which supplies the two states an environment variable never could: a build
 * constant, and a disagreement. */
#define ND_ENV_PLATFORM "NEODCT_PLATFORM"

/* The three words the file may carry, and the one it cannot. */
#define ND_PLATFORM_NAME_QEMU    "qemu"
#define ND_PLATFORM_NAME_HW      "hw"
#define ND_PLATFORM_NAME_UNKNOWN "unknown"

/* The keys inside /NeoDCT/platform. */
#define ND_PLATFORM_KEY_PLATFORM "platform"
#define ND_PLATFORM_KEY_BOARD    "board"
#define ND_PLATFORM_KEY_IMAGE    "image"

/* A board name is a short token; the longest today is
 * "luckfox-pico-mini-b". */
#define ND_PLATFORM_BOARD_MAX 64

/* One human sentence, for the diagnostics that have to show their working. */
#define ND_PLATFORM_ORIGIN_MAX 128

typedef enum { ND_PLATFORM_UNKNOWN = 0, ND_PLATFORM_QEMU, ND_PLATFORM_HW } nd_platform_t;

/* Resolved once per process and cached, the same shape as nd_path_root() and
 * nd_nap_phone_arch(): one fopen of a tiny file for the life of the process.
 * Deliberately NOT through nd_settings_get() -- nd_settings.h's R-24 quirk
 * makes every read of a key outside DEFAULTS rewrite settings.prop with an
 * fsync, and a platform check belongs in boot paths and crash handlers where
 * a flash write is exactly the wrong thing to do. */
nd_platform_t nd_platform(void);

/* "qemu", "hw" or "unknown". Never NULL, never allocated. */
const char *nd_platform_name(void);

/* The board, e.g. "luckfox-pico-mini-b" or "qemu-virt". "" when the record
 * does not name one, which is also what an UNKNOWN platform reports: half of
 * a record we could not understand is not a fact.
 *
 * The board is what makes this forward-compatible. A future dev-kit ships as
 * platform=hw board=devkit-x, every existing is_hw() branch keeps working, and
 * only the code that genuinely cares which board it is looks here. A third
 * value of the platform word would have broken all of them at once. */
const char *nd_platform_board(void);

/* Exactly ND_PLATFORM_HW, and exactly ND_PLATFORM_QEMU. Both are false under
 * UNKNOWN, which is the point -- see the rule at the top. */
bool nd_platform_is_hw(void);
bool nd_platform_is_qemu(void);

/* Where nd_platform()'s answer came from, in one line, for the diagnostics
 * that have to show their working -- nd-selftest's header, the crash log's
 * `mode:` field. Never NULL, never allocated.
 *
 * One long sentence is deliberately the whole reporting API. An
 * nd_platform_build() and a "what the record said" accessor would be branched
 * on within a month, and a caller reading the build value directly is a caller
 * bypassing the mismatch -- the same shape as the !nd_platform_is_qemu() this
 * header refuses to provide a helper for. A sentence can be printed and cannot
 * cheaply be decided on; the one boolean anybody legitimately needs is below.
 *
 * The environment's VALUE is never interpolated into it. NEODCT_PLATFORM can
 * come from env.sh, and a diagnostic line is not a place to echo text an
 * attacker wrote; an unrecognised word is reported as "ignored". */
const char *nd_platform_origin(void);

/* True when the compiled-in constant and /NeoDCT/platform name DIFFERENT
 * machines. nd_platform() is ND_PLATFORM_UNKNOWN for the life of the process
 * whenever this is true.
 *
 * It exists so a caller can FAIL CLOSED. UNKNOWN alone cannot tell the benign
 * case (a host build that was told nothing) from the alarming one (an image
 * assembled from two builds), and a gate written as "simulate unless is_hw()"
 * would let a mis-assembled phone take the emulator's branch. Anything that
 * would be dangerous to get wrong asks this as well.
 *
 * The caller it was written for is nd_modem__board_should_have_a_radio(), and
 * it is worth naming because a predicate with no callers is a predicate that
 * gets deleted: `is_hw() || mismatch()` is what stops a contested image
 * simulating its radio, and nd_modem.h has the trade written out. */
bool nd_platform_mismatch(void);

/* Tests only, like nd_path_set_root(): drop the cache so the next call reads
 * the environment and the file again. The cache exists so that a process
 * cannot see the platform change under it, which is right in production and
 * useless in a test that has just written a fixture. Does NOT clear the build
 * constant -- that is not a cached reading of anything. */
void nd_platform__reset_cache(void);

/* Tests only, the sibling of nd_platform__reset_cache(): pretend this binary
 * was built for that machine. Drops the cache as part of the call, so a case
 * cannot forget. ND_PLATFORM_UNKNOWN restores "this build was told nothing",
 * which is what every test binary in the tree actually is.
 *
 * It does not weaken the constant, and the honest framing is worth stating:
 * the value of a compiled-in constant is that it cannot be changed by DATA --
 * a file, an environment variable, a settings key -- not that it resists code
 * already linked into the address space. That is the same reasoning that
 * already justifies nd_platform__reset_cache(). A call to this from outside
 * test/ would hand the discriminator away; it is the one symbol here worth
 * grepping for in review. */
void nd_platform__set_build(nd_platform_t built_for);

#ifdef __cplusplus
}
#endif

#endif /* ND_PLATFORM_H_INCLUDED */
