/* nd_platform.h -- which machine is this, asked once and answered from the
 * image rather than guessed from the hardware.
 *
 * The answer is baked in at BUILD time. post-build-system-metadata.sh writes
 * /NeoDCT/platform into the read-only rootfs from the same $PLATFORM it uses
 * for system.os.platform, so the file cannot disagree with the image it is
 * part of, and nothing at runtime can edit it: it is inside the squashfs,
 * under dm-verity.
 *
 *     # Generated by post-build-system-metadata.sh -- do not edit.
 *     platform=hw
 *     board=luckfox-pico-mini-b
 *     image=luckfox-armv7
 *
 * ============ WHY THIS EXISTS AT ALL ============
 *
 * Half a dozen places in the tree used to work out where they were running by
 * looking for a device and drawing a conclusion: nd_crash.c and
 * nd_keypadsetup.c tested access("/dev/ttyFIQ0"), S10udevd and S90display
 * tested [ -e /dev/spidev0.0 ], KeypadMapperI2C told the owner "this cannot
 * run in QEMU" on the strength of an empty /dev/i2c-* glob. Every one of those
 * is a proxy, and a proxy is wrong in both directions: a hardware kernel built
 * without the FIQ debugger reads as QEMU, and any emulator that grew a
 * spidev node would read as a phone. The visible damage was real -- a phone
 * whose crash reports were all filed as "QEMU/simulation", and a phone that
 * skipped waiting for its own keypad bus and came up with no keys.
 *
 * ============ WHY THREE VALUES AND NOT TWO ============
 *
 * A missing or unreadable file is ND_PLATFORM_UNKNOWN, which is a genuine
 * answer and not a shorthand for either of the others. Both defaults were
 * considered and both are worse:
 *
 *   defaulting to HW arms every hardware wait on a developer's laptop and in
 *   every unit test -- the first-boot keypad wizard would sit waiting for
 *   /dev/i2c-3 on a machine that has never had one;
 *
 *   defaulting to QEMU is the 0.5.9a regression class in reverse. A real
 *   phone that lost its flag would quietly take every cheap emulator path,
 *   and nd_modem.h records what that looks like from the outside: a phone
 *   telling its owner everything is fine while its radio is unreachable.
 *
 * ============ THE RULE AT THE CALL SITE ============
 *
 * UNKNOWN may decide a COST question and may never decide a TRUTH question.
 *
 *   "Should I spend ten seconds waiting for a bus that may be coming?"  is a
 *   cost question. UNKNOWN takes the cheap branch: do not wait. Nothing is
 *   claimed; at worst a developer waits zero seconds instead of ten.
 *
 *   "Is there a radio on this board?", "is this crash report from a phone?",
 *   "should a missing i2c bus be a FAILURE rather than a skip?" are truth
 *   questions. UNKNOWN answers none of them, and a call site that needs one
 *   answered has to keep whatever evidence it already had.
 *
 * That is why the two predicates below are separate and why there is no
 * negation helper: !nd_platform_is_qemu() reads as "hardware" and is not,
 * and the day somebody writes it the phone starts making claims about
 * hardware it has never been told it has.
 *
 * ============ WHAT THIS IS NOT ============
 *
 * It is not system.os.platform. That value ("qemu-aarch64",
 * "luckfox-armv7") is the update system's compatibility key -- see
 * nd_manifest_check_compatible() and nd_remote_asset_name() -- and its format
 * is load-bearing for every .ndsw ever built. This is a sibling of it, carried
 * in the same generated block, in a file cheap enough to read from a boot
 * script; the image= key holds that same tag for anything that wants it.
 *
 * And it is not a device probe. The modem's SIM-vs-UNREACHABLE gate
 * (nd_modem.h) and the battery's SIM-vs-UNREADABLE gate (nd_battery.h) turn
 * on whether a candidate device actually enumerated, which is a different
 * question with a different failure mode; both headers record at length what
 * conflating the two cost. Do not route either of them through here.
 *
 * Two more that read like guesses and are not, listed because both have
 * already been looked at once and the reasoning should not have to be
 * rediscovered. nd_log_redirect_serial() picks /dev/ttyFIQ0 over /dev/ttyAMA0
 * by testing the node it is about to open, which is evidence about that node
 * rather than a proxy for the machine -- asking here would hand a hardware
 * kernel with no FIQ debugger a console that does not exist. And
 * nd_nap_phone_arch() (nd_nap.h) reads uname(2) because a .nap carries native
 * code: that is an ABI question about the CPU running now, it has a
 * host-x86_64 answer this file will never have, and an UNKNOWN there would
 * turn a missing flag into a phone that can install nothing. Both headers
 * carry the long version at the call site.
 */

#ifndef ND_PLATFORM_H_INCLUDED
#define ND_PLATFORM_H_INCLUDED

#include "nd_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* The environment override, checked before the file. Two callers in practice:
 * a host test that wants to be a phone for one case, and a developer bisecting
 * something under QEMU. It carries the platform word only ("qemu" or "hw") --
 * a board name has to come from a real record, because a board is a claim
 * about a piece of hardware and an environment variable is not evidence of
 * one. Anything else, including an empty value, is ignored. */
#define ND_ENV_PLATFORM "NEODCT_PLATFORM"

/* The three words the file may carry, and the one it cannot. */
#define ND_PLATFORM_NAME_QEMU    "qemu"
#define ND_PLATFORM_NAME_HW      "hw"
#define ND_PLATFORM_NAME_UNKNOWN "unknown"

/* The keys inside /NeoDCT/platform. */
#define ND_PLATFORM_KEY_PLATFORM "platform"
#define ND_PLATFORM_KEY_BOARD    "board"
#define ND_PLATFORM_KEY_IMAGE    "image"

/* A board name is a short token; the longest today is
 * "luckfox-pico-mini-b". */
#define ND_PLATFORM_BOARD_MAX 64

typedef enum { ND_PLATFORM_UNKNOWN = 0, ND_PLATFORM_QEMU, ND_PLATFORM_HW } nd_platform_t;

/* Resolved once per process and cached, the same shape as nd_path_root() and
 * nd_nap_phone_arch(): one fopen of a tiny file for the life of the process.
 * Deliberately NOT through nd_settings_get() -- nd_settings.h's R-24 quirk
 * makes every read of a key outside DEFAULTS rewrite settings.prop with an
 * fsync, and a platform check belongs in boot paths and crash handlers where
 * a flash write is exactly the wrong thing to do. */
nd_platform_t nd_platform(void);

/* "qemu", "hw" or "unknown". Never NULL, never allocated. */
const char *nd_platform_name(void);

/* The board, e.g. "luckfox-pico-mini-b" or "qemu-virt". "" when the record
 * does not name one, which is also what an UNKNOWN platform reports: half of
 * a record we could not understand is not a fact.
 *
 * The board is what makes this forward-compatible. A future dev-kit ships as
 * platform=hw board=devkit-x, every existing is_hw() branch keeps working, and
 * only the code that genuinely cares which board it is looks here. A third
 * value of the platform word would have broken all of them at once. */
const char *nd_platform_board(void);

/* Exactly ND_PLATFORM_HW, and exactly ND_PLATFORM_QEMU. Both are false under
 * UNKNOWN, which is the point -- see the rule at the top. */
bool nd_platform_is_hw(void);
bool nd_platform_is_qemu(void);

/* Tests only, like nd_path_set_root(): drop the cache so the next call reads
 * the environment and the file again. The cache exists so that a process
 * cannot see the platform change under it, which is right in production and
 * useless in a test that has just written a fixture. */
void nd_platform__reset_cache(void);

#ifdef __cplusplus
}
#endif

#endif /* ND_PLATFORM_H_INCLUDED */
