/*
 * Linux evdev keycode translation for the linux framebuffer surface.
 */

#include "linux_evdev.h"

#define EVDEV_MAP_MAX 111

/* linux input-event-codes KEY_* index -> nsfb keycode */
static const uint16_t evdev_map[EVDEV_MAP_MAX + 1] = {
	[1] = NSFB_KEY_ESCAPE,
	[2] = NSFB_KEY_1,
	[3] = NSFB_KEY_2,
	[4] = NSFB_KEY_3,
	[5] = NSFB_KEY_4,
	[6] = NSFB_KEY_5,
	[7] = NSFB_KEY_6,
	[8] = NSFB_KEY_7,
	[9] = NSFB_KEY_8,
	[10] = NSFB_KEY_9,
	[11] = NSFB_KEY_0,
	[12] = NSFB_KEY_MINUS,
	[13] = NSFB_KEY_EQUALS,
	[14] = NSFB_KEY_BACKSPACE,
	[15] = NSFB_KEY_TAB,
	[16] = NSFB_KEY_q,
	[17] = NSFB_KEY_w,
	[18] = NSFB_KEY_e,
	[19] = NSFB_KEY_r,
	[20] = NSFB_KEY_t,
	[21] = NSFB_KEY_y,
	[22] = NSFB_KEY_u,
	[23] = NSFB_KEY_i,
	[24] = NSFB_KEY_o,
	[25] = NSFB_KEY_p,
	[26] = NSFB_KEY_LEFTBRACKET,
	[27] = NSFB_KEY_RIGHTBRACKET,
	[28] = NSFB_KEY_RETURN,
	[29] = NSFB_KEY_LCTRL,
	[30] = NSFB_KEY_a,
	[31] = NSFB_KEY_s,
	[32] = NSFB_KEY_d,
	[33] = NSFB_KEY_f,
	[34] = NSFB_KEY_g,
	[35] = NSFB_KEY_h,
	[36] = NSFB_KEY_j,
	[37] = NSFB_KEY_k,
	[38] = NSFB_KEY_l,
	[39] = NSFB_KEY_SEMICOLON,
	[40] = NSFB_KEY_QUOTE,
	[41] = NSFB_KEY_BACKQUOTE,
	[42] = NSFB_KEY_LSHIFT,
	[43] = NSFB_KEY_BACKSLASH,
	[44] = NSFB_KEY_z,
	[45] = NSFB_KEY_x,
	[46] = NSFB_KEY_c,
	[47] = NSFB_KEY_v,
	[48] = NSFB_KEY_b,
	[49] = NSFB_KEY_n,
	[50] = NSFB_KEY_m,
	[51] = NSFB_KEY_COMMA,
	[52] = NSFB_KEY_PERIOD,
	[53] = NSFB_KEY_SLASH,
	[54] = NSFB_KEY_RSHIFT,
	[55] = NSFB_KEY_KP_MULTIPLY,
	[56] = NSFB_KEY_LALT,
	[57] = NSFB_KEY_SPACE,
	[58] = NSFB_KEY_CAPSLOCK,
	[71] = NSFB_KEY_KP7,
	[72] = NSFB_KEY_KP8,
	[73] = NSFB_KEY_KP9,
	[74] = NSFB_KEY_KP_MINUS,
	[75] = NSFB_KEY_KP4,
	[76] = NSFB_KEY_KP5,
	[77] = NSFB_KEY_KP6,
	[78] = NSFB_KEY_KP_PLUS,
	[79] = NSFB_KEY_KP1,
	[80] = NSFB_KEY_KP2,
	[81] = NSFB_KEY_KP3,
	[82] = NSFB_KEY_KP0,
	[83] = NSFB_KEY_KP_PERIOD,
	[96] = NSFB_KEY_KP_ENTER,
	[97] = NSFB_KEY_RCTRL,
	[98] = NSFB_KEY_KP_DIVIDE,
	[100] = NSFB_KEY_RALT,
	[102] = NSFB_KEY_HOME,
	[103] = NSFB_KEY_UP,
	[104] = NSFB_KEY_PAGEUP,
	[105] = NSFB_KEY_LEFT,
	[106] = NSFB_KEY_RIGHT,
	[107] = NSFB_KEY_END,
	[108] = NSFB_KEY_DOWN,
	[109] = NSFB_KEY_PAGEDOWN,
	[110] = NSFB_KEY_INSERT,
	[111] = NSFB_KEY_DELETE,
};

enum nsfb_key_code_e nsfb_linux_evdev_to_nsfb(uint16_t code)
{
	if (code > EVDEV_MAP_MAX)
		return NSFB_KEY_UNKNOWN;
	return (enum nsfb_key_code_e)evdev_map[code];
}
