#!/bin/sh
# A relay on this machine, so Remote Shell can be tested end to end without
# a VPS.
#
# Remote Shell dials OUT to a relay and asks it to forward a port back. That
# shape is what makes it work from behind CGNAT, and it is also what makes it
# awkward to test: it needs a real ssh server somewhere else, and the phone
# always dials that server on port 22.
#
# This runs an unprivileged sshd on 127.0.0.1:2022 and points the guest's
# 10.0.2.100:22 at it with QEMU's guestfwd, so the phone dials "port 22" and
# lands here. Everything else is real: real ssh, real sshd, real forward.
#
#   neodct/tools/test_relay.sh up          start the relay, make the keys
#   neodct/tools/test_relay.sh seed        write the keys into userdata.ext4
#   neodct/tools/test_relay.sh qemu-args   the -netdev line to pass QEMU
#   neodct/tools/test_relay.sh status      is the relay up, is the tunnel in
#   neodct/tools/test_relay.sh ssh [cmd]   log in to the phone through it
#   neodct/tools/test_relay.sh log         the phone's own remote.log
#   neodct/tools/test_relay.sh down        stop the relay
#
# The relay's state lives in $NEODCT_RELAY_DIR (default below) and is safe to
# delete; "up" regenerates it.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(dirname "$HERE")"
IMAGES="${NEODCT_IMAGES:-$(dirname "$REPO")/buildroot/output/images}"

R="${NEODCT_RELAY_DIR:-${TMPDIR:-/tmp}/neodct-test-relay}"
RELAY_PORT="${NEODCT_RELAY_PORT:-2022}"   # where our sshd listens, on loopback
PHONE_PORT="${NEODCT_PHONE_PORT:-2222}"   # what the phone asks to have forwarded
RELAY_USER="${NEODCT_RELAY_USER:-$(id -un)}"
SSHD="${NEODCT_SSHD:-/usr/sbin/sshd}"
# Not derived from IMAGES: the images may be a copy somewhere else, but
# debugfs only ever lives in Buildroot's host tree.
DEBUGFS="${NEODCT_DEBUGFS:-$(dirname "$REPO")/buildroot/output/host/sbin/debugfs}"

# 10.0.2.2 is slirp's own gateway and it refuses to guestfwd that, so the relay
# gets an otherwise unused address on the same net. The phone always dials 22.
GUEST_RELAY_ADDR=10.0.2.100

say() { echo "test_relay: $*"; }
die() { echo "test_relay: $*" >&2; exit 1; }

sftp_server() {
    for candidate in /usr/lib/ssh/sftp-server /usr/libexec/sftp-server \
                     /usr/lib/openssh/sftp-server /usr/lib/misc/sftp-server; do
        [ -x "$candidate" ] && { echo "$candidate"; return; }
    done
    echo /usr/lib/ssh/sftp-server
}

cmd_up() {
    [ -x "$SSHD" ] || die "no sshd at $SSHD"
    mkdir -p "$R"
    chmod 700 "$R"

    # The relay's own identity, and the key the phone dials in with. Both are
    # throwaway and both are regenerated only when missing, so a reboot of the
    # guest does not invalidate what was seeded into userdata.
    [ -f "$R/host_ed25519" ] || \
        ssh-keygen -q -t ed25519 -N "" -f "$R/host_ed25519" -C "neodct test relay"
    [ -f "$R/phone_key" ] || \
        ssh-keygen -q -t ed25519 -N "" -f "$R/phone_key" -C "neodct test phone"
    # The key we log in to the PHONE with, once the tunnel is up.
    [ -f "$R/client_key" ] || \
        ssh-keygen -q -t ed25519 -N "" -f "$R/client_key" -C "neodct test client"

    cp "$R/phone_key.pub" "$R/authorized_keys"
    chmod 600 "$R/authorized_keys"

    cat > "$R/sshd_config" <<EOF
# Generated by test_relay.sh. A stand-in for the VPS, on loopback only.
Port $RELAY_PORT
ListenAddress 127.0.0.1
HostKey $R/host_ed25519
AuthorizedKeysFile $R/authorized_keys
PidFile $R/sshd.pid
# We are not root, so the usual ownership rules cannot be satisfied.
StrictModes no
UsePAM no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
# The whole point: the phone asks for a reverse forward.
AllowTcpForwarding yes
GatewayPorts no
LogLevel VERBOSE
Subsystem sftp $(sftp_server)
EOF

    cmd_down >/dev/null 2>&1 || true
    "$SSHD" -f "$R/sshd_config" -E "$R/sshd.log"
    sleep 0.5
    ss -tln 2>/dev/null | grep -q ":$RELAY_PORT " || die "sshd did not listen on $RELAY_PORT"

    forwarder="${NEODCT_NETCAT:-$(command -v ncat 2>/dev/null || command -v nc 2>/dev/null || true)}"
    [ -n "$forwarder" ] || die "no ncat/nc for the guest forward; set NEODCT_NETCAT"
    printf '#!/bin/sh\nexec %s 127.0.0.1 %s\n' "$forwarder" "$RELAY_PORT" > "$R/forward.sh"
    chmod 755 "$R/forward.sh"

    # The phone checks the relay's host key, so it needs to know it under the
    # name it will dial -- 10.0.2.100, on port 22, which is the bare form.
    # known_hosts is "host keytype key" and a .pub file is "keytype key
    # comment" -- so the host goes IN FRONT, it does not replace field one.
    awk -v host="$GUEST_RELAY_ADDR" '{ printf "%s %s %s\n", host, $1, $2 }' \
        "$R/host_ed25519.pub" > "$R/known_hosts.guest"

    say "relay up on 127.0.0.1:$RELAY_PORT as $RELAY_USER"
    say "  state in $R"
}

cmd_qemu_args() {
    # cmd: and not tcp:. A guestfwd to a tcp chardev is ONE connection shared
    # by everything that dials it, so the first attempt works and every
    # reconnect after it hangs in the banner exchange -- which looks exactly
    # like a flaky relay. cmd: runs the forwarder per connection.
    # One token, no spaces: whoever passes this to QEMU word-splits it, so the
    # netcat and its arguments live in a script instead of on the command line.
    [ -f "$R/forward.sh" ] || die "run 'up' first"
    echo "-netdev user,id=eth0,guestfwd=tcp:$GUEST_RELAY_ADDR:22-cmd:$R/forward.sh -device virtio-net-device,netdev=eth0"
}

cmd_seed() {
    img="${1:-$IMAGES/userdata.ext4}"
    [ -f "$img" ] || die "no userdata image at $img"
    [ -x "$DEBUGFS" ] || die "no debugfs at $DEBUGFS"
    [ -f "$R/phone_key" ] || die "run 'up' first"

    cat > "$R/state.prop" <<EOF
enabled=1
host=$GUEST_RELAY_ADDR
user=$RELAY_USER
port=$PHONE_PORT
EOF

    # authorized_keys on the phone is what lets US in; known_hosts is what
    # lets the phone trust the relay; relay_id_ed25519 is what it dials with.
    cat > "$R/seed.cmds" <<EOF
mkdir /.remote
cd /.remote
rm state.prop
rm relay_id_ed25519
rm authorized_keys
rm known_hosts
rm remote.log
rm sshd_config
rm tunnel.sh
rm sshd.pid
rm tunnel.pid
write $R/state.prop state.prop
write $R/phone_key relay_id_ed25519
write $R/client_key.pub authorized_keys
write $R/known_hosts.guest known_hosts
quit
EOF
    "$DEBUGFS" -w -f "$R/seed.cmds" "$img" >/dev/null 2>&1 || true
    say "seeded $(basename "$img"):"
    "$DEBUGFS" -R "ls -l /.remote" "$img" 2>/dev/null | grep -vE '^debugfs' | \
        awk 'NF > 5 { printf "  %s %s\n", $6, $NF }'
}

cmd_status() {
    if ss -tln 2>/dev/null | grep -q ":$RELAY_PORT "; then
        say "relay sshd: listening on $RELAY_PORT"
    else
        say "relay sshd: DOWN"
    fi
    if ss -tln 2>/dev/null | grep -q "127.0.0.1:$PHONE_PORT "; then
        say "tunnel: the phone is dialled in ($PHONE_PORT is open)"
    else
        say "tunnel: not in"
    fi
}

phone_ssh() {
    ssh -i "$R/client_key" \
        -o IdentitiesOnly=yes \
        -o BatchMode=yes \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=ERROR \
        -o ConnectTimeout=15 \
        -p "$PHONE_PORT" root@127.0.0.1 "$@"
}

cmd_ssh() {
    if [ "$#" -eq 0 ]; then
        phone_ssh
    else
        phone_ssh "$@"
    fi
}

cmd_log() {
    img="${1:-$IMAGES/userdata.ext4}"
    "$DEBUGFS" -R "cat /.remote/remote.log" "$img" 2>/dev/null | grep -v '^debugfs'
}

cmd_down() {
    if [ -f "$R/sshd.pid" ]; then
        pid="$(cat "$R/sshd.pid" 2>/dev/null || echo)"
        [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
        rm -f "$R/sshd.pid"
    fi
    say "relay down"
}

case "${1:-}" in
    up)         shift; cmd_up "$@" ;;
    seed)       shift; cmd_seed "$@" ;;
    qemu-args)  shift; cmd_qemu_args "$@" ;;
    status)     shift; cmd_status "$@" ;;
    ssh)        shift; cmd_ssh "$@" ;;
    log)        shift; cmd_log "$@" ;;
    down)       shift; cmd_down "$@" ;;
    *)
        sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
        exit 1
        ;;
esac
